### ISSUE TITLE
--help, help, and lab/git are all inconsistent

### ISSUE THREAD

**Issue by nesl247** [zaquestion/lab#107]
After aliasing `git` to `lab`, I noticed there are several inconsistencies to the help dialog. `git --help`, `git help` and `git` all return different output. `git --help` returns the output of `lab --help`, `git help` returns the output of `hub --help` and `git` returns the output of `lab` which is a combination of hub + lab.

All of these should be returning the same output. If `hub` isn't installed, `lab` and `lab --help` should both be returning the decorated `git --help` output. If it is installed, it should be decorating the `hub --help` output.

**Comment by zaquestion** [comment]
Thanks for reporting, will get a fix up for this today or tomorrow. I'm definitely guilting of missing some edge cases that fall outside my workflow so I really appreciate the report

**Comment by zaquestion** [comment]
This is a little trickier than I thought it would be. It requires hacking around [cobras](https://github.com/spf13/cobra#help-command) built in help functionality. I managed to get the help output consistent and in the process broke all of `lab`'s help functionality. I'll need to put in some extra logic to properly execute the wrapped help when appropriate and keep `lab`'s help intact.

**Comment by zaquestion** [comment]
I think the above #108 addresses all of the issues here. It deserves some thorough tests and review given the borderline hacks required to make this work with cobra. Should be able to get tests in place this weekend and planning to upgrade cobra to see if anything in a newer version that can be put to use.

**Comment by zaquestion** [comment]
Fixed in #108 will go out in 0.9.5
