### ISSUE TITLE
SIGSEGV in gitlab.FindProject

### ISSUE THREAD

**Issue by jnv** [zaquestion/lab#109]
#Most commands I try end with the same error, e.g.:

```
$ lab snippet list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13d6564]

goroutine 1 [running]:
github.com/zaquestion/lab/internal/gitlab.FindProject(0xc42001c18c, 0x13, 0xc42001c18c, 0x13, 0x0)
	/home/travis/gopath/src/github.com/zaquestion/lab/internal/gitlab/gitlab.go:98 +0x144
github.com/zaquestion/lab/cmd.glob..func23(0x1768f00, 0x178fbc8, 0x0, 0x0)
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/snippetList.go:48 +0x2fe
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).execute(0x1768f00, 0x178fbc8, 0x0, 0x0, 0x1768f00, 0x178fbc8)
	/home/travis/gopath/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1768ac0, 0x178fbc8, 0xc42017c020, 0xc4201ba000)
	/home/travis/gopath/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).Execute(0x1768ac0, 0xc420080190, 0x2)
	/home/travis/gopath/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/zaquestion/lab/cmd.Execute()
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/root.go:168 +0x2d7
main.main()
	/home/travis/gopath/src/github.com/zaquestion/lab/main.go:65 +0x499
```

My company runs GitLab on internal VPN with custom domain `git.ccl`, so my lab.hcl looks like this: 

```
"core" = {
  "host" = "https://git.ccl"

  "token" = "<removed>"

  "user" = "<removed>"
}
```

The project where I try to run lab in has SSH remote (i.e.: `origin git@git.ccl:group/project-name.git`).

Version info:
macOS 10.13.3 (17D47)
git version 2.16.1
hub version 2.2.9
lab version 0.9.4 (via brew)

I am not sure if there is any flag or env variable to crank up verbosity. What other information can help you?

**Comment by zaquestion** [comment]
Did this start happening after an upgrade?  Was it ever working?

**Comment by jnv** [comment]
I don't remember getting it ever working on my work Mac with our internal GitLab, so I thought I'd check back later.

**Comment by zaquestion** [comment]
@jnv I'm wondering if this could be a result of lab not playing nice with existing repositories. Couple more things I'm wondering.

Do you use something like thiis to remap https to ssh? `git remote -v` will still show the remote as ssh, but catting the file will show the true remote. lab only works with ssh urls and happens to read the file directly, the first part will be fixed in #12 
```
git config --global url."git@github.com:".insteadOf "https://github.com/"
```

Second, can you try cloning with lab's org/repo syntax to see if it figures it out.
```
lab clone someorg/somerepo
```

**Comment by jnv** [comment]
Thanks for suggestions! In the end the problem was, as usual, between keyboard and chair, because VPN was disabled and I couldn't reach the host. The SIGSEGV error now makes sense to me, because the line where it happens checks for `resp.StatusCode` first and for `err` later: https://github.com/zaquestion/lab/blob/f37999cdea1080ba055942c1e53af130261ed2af/internal/gitlab/gitlab.go#L97-L103
If the host cannot be reached, you get error and no response.

**Comment by zaquestion** [comment]
Thats a huge relief! I'll leave this open as a task to fix the error handling.

**Comment by zaquestion** [comment]
Added a nil check in #110 which allow the error to be caught without panicing 
```
2018/02/17 13:42:50 mrList.go:38: Get https:/api/v4/projects/zaquestion%2Ftest: dial tcp: lookup gitlab.com on [::1]:53: server misbehaving
```
Still not the friendliest, but its better than a panic I'll say.

**Comment by jnv** [comment]
Excellent, thank you!
