### ISSUE TITLE
`lab clone` without url causes panic instead of printing help

### ISSUE THREAD

**Issue by hasLeland** [zaquestion/lab#11]
## What was expected?

When running `git clone` without specifying a url, I get a help message:

```
$ git clone
You must specify a repository to clone.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
...
...
```

## What happened instead?

When I ran `lab clone` without a url, `lab` panic'd:
```
$ lab clone
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x58350f]

goroutine 1 [running]:
github.com/zaquestion/lab/vendor/github.com/spf13/cobra.(*Command).ParseFlags(0x9c6a40, 0xc42000c310, 0x1, 0x1, 0x9c6a40, 0x9e69a0)
	/home/leland/projects/go-projects/src/github.com/zaquestion/lab/vendor/github.com/spf13/cobra/command.go:1267 +0x3f
github.com/zaquestion/lab/cmd.Execute()
	/home/leland/projects/go-projects/src/github.com/zaquestion/lab/cmd/root.go:81 +0x122
main.main()
	/home/leland/projects/go-projects/src/github.com/zaquestion/lab/main.go:6 +0x20
```

## How might this be fixed?

From what I can see in the `cmd/root.go` file, the problem is in [an unchecked slice of the `os.Args` slice on line 81.](https://github.com/zaquestion/lab/blob/f9c140fdce21cd24095bcdc58cd92bfc0fdda20f/cmd/root.go#L81) Directly above that line is a somewhat confusing comment which may or may not have anything to do with this issue, I had a hard time understanding it, though it may be of some use to whoever choses to fix this.

The change would be to check if `clone` has been provided without any additional arguments/parameters, and if it has, to print a help message in some way. The printing of a help message could be done by dropping down to gits help message or by printing `lab`s own custom help message.

**Comment by zaquestion** [comment]
@hasLeland Thanks for reporting! I've put in a fix. This issue still needs tests to close.

**Comment by bmess** [comment]
I apologize for beating a dead horse but I think this might be an elegant solution for an elegant tool :100:

**Comment by bmess** [comment]
I believe this is fixed.  Tested with `0.5.0`. I closed the MR
