### ISSUE TITLE
lab mr complains that gitlab project not found

### ISSUE THREAD

**Issue by dpetrov** [zaquestion/lab#114]
I am kind of lost.

I cloned a self-hosted repo on gitlab and I am trying to create a merge request or list all merge requests, but I am getting:

```
[dpetrov@macbook-pro /tmp/apps (master)]$ lab mr list
2018/03/06 22:40:58 mrList.go:38: gitlab project not found
```

Is there something that i am missing?

Thanks

**Comment by zaquestion** [comment]
Hi @dpetrov can you let me know what version of lab you're using?
```
lab version
```
and what you remotes look like?
```
git remote -v
```
It would also be useful to know how you cloned the repo you're trying this on. `lab mr list` is a fairly simple command so the most likely problems are:
- lab cannot parse/understand what project to lookup on gitlab
- invalid api token
- wrong gitlab host (please double check your `~/.config/lab.hcl` for correctness)

**Comment by dpetrov** [comment]
Hey @zaquestion,

thanks for the feedback.

I am using the latest lab version (0.9.5) however I think what might be causing the issue.
```
$ lab version
git version 2.7.4
lab version 0.9.5
```
Our self-hosted version is hosted at: https://gitlab.internal/scm.

Here is the output:
```
$ git remote -v
origin	git@gitlab.internal:apps/play.git (fetch)
origin	git@gitlab.internal:apps/play.git (push)
```

The token is correct and the host that I got is:
```
"core" = {
  "host" = "https://gitlab.internal/scm"
```
I think that the subfolder path is causing the issue tbh.

**Comment by zaquestion** [comment]
@dpetrov Thats a solid theory, I'll peak at that code tonight, I'm guessing that I'm trimming off the path when I join the path to the API. In the mean time can you confirm what your api path would be?
This?
```
https://gitlab.internal/scm/api/v4/projects
```

**Comment by zaquestion** [comment]
@dpetrov It looks like lab does combine your host value exactly with the API path
```
	lab.SetBaseURL(host + "/api/v4")
```
https://github.com/zaquestion/lab/blob/master/internal/gitlab/gitlab.go#L46

Based on your remote setup which points directly at the `gitlab.internal` endpoint I'm guessing your API endpoint _is_ at (without subfolder path)
```
https://gitlab.internal/api/v4/projects
```

You can test this out by curling the projects endpoint, without authentication you should get an empty array back
```
$ curl "https://gitlab.company/api/v4/projects"
[]
```
a bad path will return
```
$ curl "https://gitlab.company/scm/api/v4/projects"
<html><body>You are being <a href="https://gitlab.company/users/sign_in">redirected</a>.</body></html>
```

**Comment by dpetrov** [comment]
@zaquestion yep, the URL is correct and I can retrieve a list with all projects. Thanks so much.

**Comment by zaquestion** [comment]
Well then :), can you try an authorized request to verify the token is working?
```
curl --header "Private-Token: REPLACE_WITH_TOKEN" https://gitlab.internal/scm/api/v4/projects
```
Assuming there are projects in the instance that should just be a non empty list.

**Comment by dpetrov** [comment]
Sure thing, here it is ;)

```$ curl --header "Private-Token: QFzbaLy3b2gQHzjUvLDo" https://gitlab.internal/scm/api/v4/projects
[{"id":27,"description":"..."
```

**Comment by zaquestion** [comment]
Hmm, well this would seem to be an issue with lab. Is there anything you can tell me about how the server is configured to be at that path? GitLab setting? nginx proxy?

**Comment by dpetrov** [comment]
We do have apache as frontend proxy.

Here is the basic configuration:
``` 
#GITLAB Configuration
<Location /scm>
    ProxyPass http://localhost:8083/scm
    ProxyPassReverse http://127.0.0.1:8083/scm
  </Location>
```

into gitlab.conf have to be configured as well, so all URLs, Emails, hooks, etc to work as expected.

`gitlab-rails/env/RAILS_RELATIVE_URL_ROOT:/scm`

Anything else, that might help you? Is there any way I can enable `lab` in debug mode?

**Comment by zaquestion** [comment]
@dpetrov One more API call for you to try if you're up for it
```
curl --header "Private-Token: QFzbaLy3b2gQHzjUvLDo" https://gitlab.internal/scm/api/v4/projects/apps%2Fplay
```
This should match the call lab is making, if it works it may indicate an issue with the go-gitlab client

**Comment by dpetrov** [comment]
Here is a bit more information:

```
$ curl --header "Private-Token: QFzbaLy3b2gQHzjUvLDo" https://gitlab.internal/scm/api/v4/projects/apps%2Fplay
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /scm/api/v4/projects/apps/play was not found on this server.</p>
</body></html>
```

From retrieving all the projects, here is the info about the project itself:

```
   {
      "id":14,
      "description":"",
      "name":"play",
      "name_with_namespace":"Apps / play",
      "path":"play",
      "path_with_namespace":"apps/play",
      "created_at":"2018-01-25T13:23:34.059+02:00",
      "default_branch":"master",
      "tag_list":[  ],
      "ssh_url_to_repo":"git@gitlab.internal:apps/play.git",
      "http_url_to_repo":"https://gitlab.internal/scm/apps/play.git",
      "web_url":"https://gitlab.internal/scm/apps/play",
      "avatar_url":null,
      "star_count":0,
      "forks_count":0,
      "last_activity_at":"2018-02-09T07:14:38.210+02:00",
      "_links":{  },
      "archived":false,
      "visibility":"private",
      "resolve_outdated_diff_discussions":false,
      "container_registry_enabled":true,
      "issues_enabled":true,
      "merge_requests_enabled":true,
      "wiki_enabled":false,
      "jobs_enabled":true,
      "snippets_enabled":true,
      "shared_runners_enabled":true,
      "lfs_enabled":true,
      "creator_id":32,
      "namespace":{  ... },
      "import_status":"none",
      "open_issues_count":0,
      "public_jobs":false,
      "ci_config_path":"",
      "shared_with_groups":[ ... ],
      "only_allow_merge_if_pipeline_succeeds":false,
      "request_access_enabled":false,
      "only_allow_merge_if_all_discussions_are_resolved":false,
      "printing_merge_request_link_enabled":true,
      "permissions":{  ... }
   },
```

So if I try to retrieve the project by ID it seems to work fine:

For example: `https://code.irisns.com/scm/api/v4/projects/14`. Reading a bit further about the Gitlab API (https://docs.gitlab.com/ce/api/README.html#namespaced-path-encoding) that seems to be supported.

So it looks like not code issue I guess, but either the setup or something else that I am missing.

**Comment by zaquestion** [comment]
I wonder if it could be a similar issue to this https://gitlab.com/gitlab-org/gitlab-recipes/issues/36
where the "%2F" ( "/" ) is being decoded at the apache level and causing the search to fail when it gets to gitlab

**Comment by dpetrov** [comment]
Just what I thought (and found). I think the reverse proxy is breaking it. Let me try something quickly and will provide a short update. Thanks for the help.

**Comment by zaquestion** [comment]
Admittedly my apache is pretty rusty, but there seems to be some kind of
```
    AllowEncodedSlashes NoDecode
```
which someone pasted in an apache config for gitlab here: https://gitlab.com/gitlab-org/gitlab-recipes/merge_requests/62
(possibly this is exactly what you're trying) Good Luck!

**Comment by dpetrov** [comment]
I am getting a step closer to isolate the issue. If I query directly the Gitlab backend, I see the result:

```
curl --header "Private-Token: zQVtyJdVG4cSc5VPdKi6" http://localhost:8083/scm/api/v4/projects/apps%2Fplay
{"id":14,"description":"","name":"play","name_with_namespace":"Apps / play","path":"play",
```

So I guess it's the frontend proxy. I'll update with a quick example once fixed, just for the sake of completeness.

**Comment by dpetrov** [comment]
@zaquestion thanks you so much for your time and the effort.

Indeed adding AllowEncodedSlashes did fix the issue. Here is the result:

```
$ curl --header "Private-Token: zQVtyJdVG4cSc5VPdKi6" https://gitlab.internal/scm/api/v4/projects/apps%2Fplay
{"id":14,"description":"","name":"play","name_with_namespace":"Apps / play","path":"play",
```

Thanks!
