### ISSUE TITLE
Support mr create target

### ISSUE THREAD

**Issue by dpetrov** [zaquestion/lab#115]
It would be awesome, if a target could be specified during a merge request. I was thinking something like:

`$ lab mr create --target play-1.2`

**Comment by zaquestion** [comment]
@dpetrov `lab` currently supports `lab mr create [remote]` to create the mr on the specified remote.

In an effort to align with `git` where possible what do you think about 
```
lab mr create [remote [branch]]
```
where `[branch]` would be the target and your current branch would be the source as usual. This should be pretty easy to implement as well and could probably go out in `0.10`

**Comment by dpetrov** [comment]
hey @zaquestion,

`lab mr create [remote [branch]]` looks great. Would `lab mr create [remote]` create a merge-request against `master` or the currently branched source?

For example: the developer is working on Jira PLAY-123 which is Bug in release `play-1.x`. The developer branches from `play-1.x` and would like to send a merge request against that same release branch?

Thanks

**Comment by zaquestion** [comment]
@dpetrov Added support for `lab mr create [remote [branch]]` expect to see it release in `0.10.0` sometime next week. I'm going to try and finish up the other `0.10.0` milestone items today so currently targeting monday.

To answer your question `lab mr create [remote]` will only set the remote you're going to mr against essentially origin/upstream vs user fork. Its not aware what branch you checkout out from, so it also only targets master as you suspected.

**Comment by dpetrov** [comment]
awesome, thanks so much for the feedback and including it into the `0.10.0` release. It's much appreciated.

**Comment by dpetrov** [comment]
@zaquestion is there anything from my side that I can do to get the 0.10.0 rolling? Anything you might need help with?

**Comment by zaquestion** [comment]
@dpetrov Sorry for the delay! I ended up on vacation before I finished everything up. That has the released pushed back to this weekend when I return.

Everything in the 0.10 milestone is tagged. There are a couple MRs up that need some tests and a bug that's unstarted I'd like to make the cut, but that can be pushed back to a patch release

**Comment by dpetrov** [comment]
no worries ;) I hope you are enjoying your vacation.

**Comment by zaquestion** [comment]
@dpetrov [v0.10](https://github.com/zaquestion/lab/releases/tag/v0.10.0) is released

**Comment by dpetrov** [comment]
Thanks!
