### ISSUE TITLE
Support remote origin over http or https

### ISSUE THREAD

**Issue by adamryman** [zaquestion/lab#12]
`lab` seems to have issues if remote `origin` is of type `http` or `https` rather than `ssh` in the `.git/config` file.

To illustrate:

This works:
```
[remote "origin"]
	url = git@gitlab.com:foo/bar.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

This does not work:
```
[remote "origin"]
	url = https://gitlab.com/foo/bar.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by zaquestion** [comment]
Should be fixed in #111, re-open if any new cases come up.
