### ISSUE TITLE
Deprecate the short hand `lab merge-request` ? and use `lab mr create origin master`

### ISSUE THREAD

**Issue by jspreddy** [zaquestion/lab#137]
`lab merge-request` can probably be deprecated as it does the same thing as `lab mr create origin master`

**Comment by zaquestion** [comment]
It even works the same as a normal `lab mr create` I'd love to deprecate it but left it around since I added it before the other command. 

That said, it seems like a good idea to put a deprecation notice in the next release and remove for 1.0

**Comment by zaquestion** [comment]
Removed this from `lab help`, but left the command in there for anyone still using it. Should help keep the help text clean. Removed the deprecation notice added by an earlier commit, I think its fine to support in the long run, but doesn't need to be called out in the docs.

**Comment by zaquestion** [comment]
Released in `0.11.0`
