### ISSUE TITLE
add support for merge request approval

### ISSUE THREAD

**Issue by fahrradflucht** [zaquestion/lab#146]
it would be great if lab could support [merge request approval](https://docs.gitlab.com/ee/api/merge_request_approvals.html#approve-merge-request) which is a feature necessary to merge on a lot of Gitlab EE instances.

**Comment by zaquestion** [comment]
I knew this day would come eventually :grinning: -- I'll add functionality for approval in the next release, but we'll still likely be missing proper support for actually reviewing MRs on the cli.

**Comment by zaquestion** [comment]
Put up https://github.com/xanzy/go-gitlab/pull/386 to support this in the go-gitlab API. Once thats in it'll be easy to add this functionality the same way `lab mr merge` works.

There are some other changes I'd like to bring along if they prove simple enough.
- Support thump up/down on merge requests (this is actually what my work uses over the approval system for whatever reason)
- Allow all of the mr operations to work in the context of a `lab mr checkout` / matching branch
  - This is to step forward solid mr review workflows with lab
  - Personally I'll go insane if I have to keep remembering and typing the mr id for every command

**Comment by zaquestion** [comment]
@fahrradflucht I accidentally missed this in the last release. I had most of it finished, but didn't realized it was never pushed/merged until it was too late. I'll try and get it finished up soon and do a smaller release.

**Comment by zaquestion** [comment]
@fahrradflucht Sorry for the long delay, basic `lab mr approve <id>` support is included in `v0.13.0`. I've also included thumb operations on `lab mr thumb`, but be aware they don't currently support removing the thumbs.

**Comment by FanyiZeng** [comment]
`lab mr approve 5243`

> mr_approve.go:30: POST https://gitlab.*.com/api/v4/projects/294/merge_requests/5243/approve: 404 {error: 404 Not Found}

maybe the api is changed

**Comment by kreig303** [comment]
```
➜  lab mr approve 38 
2020/06/15 08:55:31 mr_approve.go:30: POST https://gitlab*.co/api/v4/projects/xxx/merge_requests/xx/approve: 401 {message: 401 Unauthorized}
➜ ```

@FanyiZeng something similarish save for the fact it `401`s yet other operations work correctly.

**Comment by prarit** [comment]
@zaquestion looks like this can be closed?

**Comment by kreig303** [comment]
@prarit idk... let me see if this works now?

**Comment by prarit** [comment]
@kreig303 thanks for the quick test!
