### ISSUE TITLE
Add a gif showing clone->fork->mr create workflow

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#148]

**Comment by zaquestion** [comment]
Yeah a gif showing off how to use lab seems long overdue.

**Comment by hasLeland** [comment]
I know how to create these gifs and have made them for other projects before. For an example, see here: https://github.com/lelandbatey/defuse_division

I'm going to give it a try.

**Comment by lelandbatey** [comment]
Alright, here's the gif:
![Gif of using lab workflow](http://lelandbatey.com/files/lab-demonstration-gifs/lab-demo--800x450.gif)

**Comment by zaquestion** [comment]
GIF is live front and center! Thanks @lelandbatey!
