### ISSUE TITLE
Add `lab project browse` to open the project in the browser

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#149]
`cmd/issue_browse.go` and `cmd/mr_browse.go` can be used as reference here.

**Comment by albfan** [comment]
I do almost everything from command line, but this hub feature is really appreciated for me.

I will take a look into those files, but: Will be feasible to detect origin is a gitlab repo and navigate to it directly?

**Comment by zaquestion** [comment]
@albfan If I understand, yes, thats how its currently working for issues and merge requests. `lab project browse` would open your browse to origin by default or to the desired remote with `lab project browse <remote>`. This should be relatively straightforward to implement and there are some example tests IIRC.

**Comment by albfan** [comment]
I reread my comment.

I mean if we can do

    lab browse

to behave as `hub browse` if it is a github repo or as `lab project browse` if it is a gitlab repo.

**Comment by zaquestion** [comment]
`lab browse` since it is not recognized by lab will do a `hub browse` currently. It we want it to be able to do a `lab project browse` it's a bit extra work, but I'm not against it

**Comment by zaquestion** [comment]
@albfan this is supported as off `0.12.0`, sorry for the delay!
