### ISSUE TITLE
 Usage errors after installing with HEAD

### ISSUE THREAD

**Issue by albertri87** [zaquestion/lab#150]
no gitlab-cli command works. I have added the web path to both the git config and the config token and also to the environment variables. Once I launch the commands I receive the following error. This is my configuration, and the commands that I have executed

After install gitlab-cli:

<a href="https://imgbb.com/"><img src="https://image.ibb.co/jcgmFd/gitlab_version.png" alt="gitlab_version" border="0"></a>

The route i try to merge request

<a href="https://imgbb.com/"><img src="https://image.ibb.co/bZqP1J/route.png" alt="route" border="0"></a>

How i get gitlab token 

<a href="https://ibb.co/hzSRFd"><img src="https://preview.ibb.co/fK9v8y/token_config.png" alt="token_config" border="0"></a>

Config account with profile/token 

<a href="https://ibb.co/gZ0fad"><img src="https://preview.ibb.co/hx8Yvd/lab_config.png" alt="lab_config" border="0"></a>

Errors commands

<a href="https://imgbb.com/"><img src="https://image.ibb.co/j602oy/fail.png" alt="fail" border="0"></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/eDZj1J/fail2.png" alt="fail2" border="0"></a>

**Comment by zaquestion** [comment]
@albertri87 Are you possibly trying to use https://github.com/vishwanatharondekar/gitlab-cli ?

The errors you pasted look like JavaScript errors and this tool is built in go. Likewise we moved away from gitconfig based configuration and the latest release is `0.11.1`

If your goal is to use this tool, I'd suggest either uninstalling the other one or ensuring that this one comes first in your path.

**Comment by zaquestion** [comment]
If you use the install script, `lab` will install into `/usr/local/bin/lab`, from source would be `$GOPATH/bin/lab`

**Comment by albertri87** [comment]
But where i need to execute this commands? request merge or browse command. When installing not specified in the site, what he did was to open a window to be able to execute the commands and that the console returned me "The command is not recognized"

**Comment by zaquestion** [comment]
Hey @albertri87, lets see if we can work through this, it sounds like theres some confusion around how to use lab or possibly some issues reaching it post-installation. Taking things from the top:

- What operating system are you trying to use lab on?
- How did you install lab? Is it in your `$PATH`?
- Can you paste a current `lab version`. It should look something like:
```
$ lab version
git version 2.16.2
lab version 0.11.1
```
- The commands in your description are _not_ valid `lab` commands, they use the other tool's syntax. Can you paste the current commands you're trying?
  - `lab mr create` or `lab merge-request` will open an editor for you to create an MR (from current branch to master)
  - You can view the docs here: https://zaquestion.github.io/lab/
  - You can view help on the command line with `lab <cmd> -h`

**Comment by zaquestion** [comment]
@albertri87 are you still trying to figure this out?

**Comment by zaquestion** [comment]
@albertri87 I'm going to close this out, feel free to reach back out if you still need help.
