### ISSUE TITLE
MR add Assignee flag support

### ISSUE THREAD

**Issue by EuanChan** [zaquestion/lab#154]
Is it possible to support assignee flag when create merge request.

:D

**Comment by zaquestion** [comment]
I feel like this might be a little tricky and require the user id  instead of just being able to thread a name through. Would accept a merge request that added the flag in `cmd/mrCreate.go`. Otherwise will add after getting through some other stuff, not sure on timeline atm.

**Comment by leolelego** [comment]
Love this too for issues !
like `lab issue create --to @will`

**Comment by zaquestion** [comment]
@EuanChan @leolelego This is supported on MRs and issues as of `0.12.0`

**Comment by zaquestion** [comment]
Use
```
--assignee, -a <username>
```
