### ISSUE TITLE
Prevent disastrous upstream push errors

### ISSUE THREAD

**Issue by tydavis** [zaquestion/lab#162]
For those who have forked a project but _also_ have write access to `master` on
the origin/upstream repository, use the `set-url` option to modify the upstream
remote Push endpoint to the forked repository. 

Example:

```text
M:zaquestion user$ git clone https://github.com/zaquestion/lab.git
Cloning into 'lab'...
remote: Counting objects: 3844, done.
remote: Total 3844 (delta 0), reused 0 (delta 0), pack-reused 3844
Receiving objects: 100% (3844/3844), 8.79 MiB | 22.33 MiB/s, done.
Resolving deltas: 100% (1405/1405), done.
M:zaquestion cm0l$ cd lab/
M:lab user$ git remote set-url --push origin https://github.com/tydavis/lab.git
M:lab user$ git remote -v
origin	https://github.com/zaquestion/lab.git (fetch)
origin	https://github.com/tydavis/lab.git (push)
M:lab user$ 
```

Relevant image from [this github blog post][1]:
https://cloud.githubusercontent.com/assets/1319791/8943755/5dcdcae4-354a-11e5-9f82-915914fad4f7.png

[1]:https://blog.github.com/2015-07-29-git-2-5-including-multiple-worktrees-and-triangular-workflows/#improved-support-for-triangular-workflows

**Comment by bmeneguele** [comment]
Sorry, I didn't understand what's the request/issue for lab with this issue.
I understand what you're doing and I personally do that some times, but usually I prefer to keep two different and well separated remotes for different trees and `git remote set-url --push <name> ""`, thus I have an empty push url :).
