### ISSUE TITLE
lab mr list is hardcoded to return a max of 10 merge requests

### ISSUE THREAD

**Issue by nhpolanco** [zaquestion/lab#178]
There is no way to retrieve more than 10 MR (with a specific label) at a time, since perPage in the lab mr list command is harcoded to 10. Ideally, [This line](https://github.com/zaquestion/lab/blob/fd6dda2f3cdef4d1e3f199ffb6a6440513408ee0/cmd/mr_list.go#L31) would be set dynamically via a cli flag;

**Comment by zaquestion** [comment]
`--per-page, -n` or something make sense to you?

**Comment by nhpolanco** [comment]
yeah, definitely not a go expert, but i've attempted to introduce a per page flag here: https://github.com/zaquestion/lab/pull/179

@zaquestion

**Comment by zaquestion** [comment]
@nhpolanco, sorry for the delayed response! I just got back from vacation, I'll take a look probably tomorrow.

The next release is just around the corner pending some tests for the current open pull requests, we should been able to get this change in as well

**Comment by zaquestion** [comment]
@nhpolanco Released support in `0.12.0`, thanks for contributing!
