### ISSUE TITLE
Show "downstream" jobs in `lab ci view`

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#182]
https://docs.gitlab.com/ee/ci/multi_project_pipelines.html

**Comment by zaquestion** [comment]
May be blocked by https://gitlab.com/gitlab-org/gitlab-ce/issues/44209

**Comment by zaquestion** [comment]
Looks like the "list bridge pipelines" api would expose a path to implementing this https://docs.gitlab.com/ee/api/jobs.html#list-pipeline-bridges

**Comment by bmeneguele** [comment]
Support for multi-project pipelines were added through PR #579
