### ISSUE TITLE
Support markdown in issues

### ISSUE THREAD

**Issue by jwkicklighter** [zaquestion/lab#197]
I'm not really sure the best title but the issue: it would be nice to use `#` in issue descriptions to specify markdown headers, but this unfortunately notates a commented line that won't be sent to the API.

**Comment by zaquestion** [comment]
I was thinking about this the other day, it's still possible to use `==` to specify titles, but yeah we did kind break `#`.

It's possible to change your gitCommentChar to something else and this will start working how you expect. Other than that I'm not sure the best way to address..

**Comment by hasLeland** [comment]
Ha, I just ran into this same problem where I attempted to use the standard \# to indicate a title, and instead just commented out the title from the MR. If possible, an escape character would be very helpful.

**Comment by zaquestion** [comment]
Put in a change (above) to support `\#` as an escaped comment char. Hoping to get a release out tonight.
