### ISSUE TITLE
FR: `lab project create` for a different namespace

### ISSUE THREAD

**Issue by krlmlr** [zaquestion/lab#211]
```
lab project create --namespace 7

# Even better:
lab project create group/repo
```

The GitLab API seems to require a numeric namespace identifier, which needs to be looked up. We might want to implement a `groups` command too.

**Comment by zaquestion** [comment]
Agree you should be able to just type the namespace along with the project. It's what feels natural

**Comment by abeluck** [comment]
This would be really great!

**Comment by bmeneguele** [comment]
Feature added with MR #450
