### ISSUE TITLE
install.sh cannot determine latest version of lab

### ISSUE THREAD

**Issue by urzds** [zaquestion/lab#212]
`install.sh` executes `curl -sL "https://github.com/zaquestion/lab/tags" | grep tag-name` to determine the latest version of `lab`.  This command has no output.  Hence the rest of the script fails.

I would suggest to instead use the GitHub API to determine the latest version.

**Comment by zaquestion** [comment]
@urzds Thanks for the heads up! The issue should be resolved now, I've switched the logic to use the GitHub API
