### ISSUE TITLE
lab pr fails

### ISSUE THREAD

**Issue by MartinDelille** [zaquestion/lab#214]
I think this feature hasn't been ported yet:

```
$ lab pr list
Aborted: the origin remote doesn't point to a GitHub repository.
```

**Comment by alerque** [comment]
The `pr` subcommand would be supplied by `hub`, not by `lab` at all. Gitlab uses "Merge Request" instead of "Pull Request" and the corresponding subcommand is `lab mr list`.

Are you sure you aren't just trying to use a Github idiom on a Gitlab based upstream repository?

**Comment by zaquestion** [comment]
@MartinDelille, @alerque's comment is spot on, I'm going to close this out, please feel free to follow up if there's any more confusing or if you ahve any feedback.

**Comment by MartinDelille** [comment]
Ok sorry I feel stupid now :sweat:

Maybe a more descriptive message would be more helpful for fool like me? :wink:

ie:
```
$ lab pr list
Aborted: the origin remote doesn't point to a GitHub repository.
Use 'lab mr' for Gitlab repository.
```
