### ISSUE TITLE
MR ls number parameter is not backwards compatible

### ISSUE THREAD

**Issue by G07cha** [zaquestion/lab#215]
Hey, I really like using your tool but recently when I've upgraded from 0.12.x to 0.13.x I discovered that `perPage` parameter was changed to `number` in `lab mr ls`. And I was surprised to see it's gone without any depredication warnings or major version update. Is it ok for you if I update this parameter to be  backward compatible?

**Comment by zaquestion** [comment]
@G07cha, yeah the big change was removing pagination from the user. Instead of specifying the items per page you just specify how may items you want total and we fetch them.

There isn't really a way to keep per page anymore since the field is set automatically based on the number. What's causing you to need perpage?

**Comment by G07cha** [comment]
That's true, I don't really find any issues with `number` parameter, in particular, I'm just confused with the way how it was handled according to semantic versioning. I also need to make sure that all of my coworkers updated their `lab` CLI to the latest version.

**Comment by zaquestion** [comment]
@G07cha yeah, I concede its a pretty clear break in semantic version. For some context we made these changes from #185 where we concluded that the existing functionality wasn't useful. 

Appreciate the feedback here, this is my first project with any attention and as a pet project its still hard for me to imagine that some changes impact people, particularly when the existing implementation feels broken.

Taking a look at the backlog, there isn't anything else that should introduce breaking changes until `1.0` and I'll keep this in mind should things come up. Likewise if theres anything you and your team would like to see please open more issues!
