### ISSUE TITLE
Open the current merge request with lab mr -b

### ISSUE THREAD

**Issue by MartinDelille** [zaquestion/lab#218]
When I'm working on a branch, I'd like to open the current merge request.

Currently I need to list the merge request like this:

```
$ lab mr list
#90 WIP: Resolve "memory leak"
#104 WIP: Resolve "Export to adobe"
#14 WIP: Resolve "Port to iOS"
```

Then browse the one I'm working on:

```
$ lab mr b 90
```

This would be nice to be able to directly open the merge request from the current branch like this:

```
$ lab mr b
```

**Comment by zaquestion** [comment]
Completely agree and it's definitely on the roadmap. The next big thing is an MR review workflow for the cli. The ability to do the above among other contextual mr tasks is first up.

**Comment by zaquestion** [comment]
Would definitely accept an mr ;)

**Comment by MartinDelille** [comment]
Currently the comand `lab mr b` open `https://gitlab.delille.org/mygroup/myproject/merge_requests`.

Should we keep this behavior?

I would propose to change my command to `lab mr o` (`o` for open).

Any idea how to query the go mr from the current branch?

I'm learning Go so I'll be happy to contribute but I might need a little help!

**Comment by zaquestion** [comment]
It seems like we should always open the current mr, unless we can't determine it (like if there isn't an me yet).

There should be a way to do it with the API, if you tried to open an mr that already exists for a branch it will complain for example, so I imagine the logic is there to look up my by branch

**Comment by zaquestion** [comment]
Looks like the API supports this https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests

I'd suggest listing all the MR with `source_branch=<current branch>`. We'll need rules on how to pick the correct MR. Something like use the MR where the target is `master`, else use the first MR in the list.

**Comment by zaquestion** [comment]
Looks like we've already got a function for listing the MRs here:
https://github.com/zaquestion/lab/blob/master/internal/gitlab/gitlab.go#L187

Probably we'll want to write a new function which calls `MRList` and used the logic in the previous post and somehow wire that into the beginning of `cmd/mr_browse.go` so that if we find an MR and no arguments were provided we use that.

**Comment by MartinDelille** [comment]
Ok I have an issue getting lab:

```
$ go get github.com/zaquestion/lab
...
../go/src/github.com/zaquestion/lab/cmd/ci_view.go:323:61: undefined: tview.ANSIIWriter
```

The error is located [here](https://github.com/zaquestion/lab/blob/master/cmd/ci_view.go#L323).

**Comment by zaquestion** [comment]
I still need to upgrade to modules so right now dependencies are managed with deep

```
go get -u -d github.com/zaquestion/lab
cd $GOPATH/src/github.com/zaquestion/lab
dep ensure
```

**Comment by zaquestion** [comment]
https://github.com/golang/dep

**Comment by zaquestion** [comment]
That's lab looking at the current directory to get the project name, but using the configured hostname. Usually I use a command like `go install $GOPATH/github.com/zaquestion/lab && lab mr browse` in a test directory
