### ISSUE TITLE
Homogeinize command between gitlab and github project

### ISSUE THREAD

**Issue by MartinDelille** [zaquestion/lab#230]
In order to homogeinize lab for github and gitlab project it would be nice to use the same commands.

Here are a few suggestions:

- [ ] alias `r` command for `mr` and `pr`
- [ ] implement `b`/`browse` command for `pr` command`

There might be some other command to homogenize but I simply propose the one I use.

**Comment by MartinDelille** [comment]
@zaquestion any thought about this?

**Comment by zaquestion** [comment]
Yes, under the current roadmap we're planning to remove the logic that wraps the `hub` and `git` binaries. Instead we'll setup as a git "extension" and use git aliases to achieve the same syntax users get when aliasing git=lab. I'm all for a homogenized command structure for working with gitlab and github, I just don't think lab should own that logic. I'd love to see a separate project join the lab and hub projects and I may even write it.

**Comment by bmeneguele** [comment]
With commit d3da0ada671ed708a6d0a425df27a6e798f73d40 (v0.21.0) `lab` dropped any `hub` command/wrapping support, therefore this issue isn't applicable anymore.
