### ISSUE TITLE
Support download of CI-uploaded artifacts

### ISSUE THREAD

**Issue by orevial** [zaquestion/lab#232]
It would be really helpful to be able to download artifacts uploaded during CI process.
In Gitlab the artifacts can be downloaded through `/jobs/{jobId}/artifacts/download`. 

Example of useful command to download the artifacts of the CI build:
`lab ci download`
or: 
`lab ci artifacts`

**Comment by zaquestion** [comment]
I'm into it!

**Comment by zaquestion** [comment]
Ref: https://docs.gitlab.com/ce/api/jobs.html#download-the-artifacts-archive

**Comment by zaquestion** [comment]
Thoughts:
`lab ci artifacts` seems like a great option for downloading the entire artifacts archive. The same syntax we use for `lab ci trace` should work well.
```
	Use:     "trace [remote [[branch]:<job>]]",
```
Effectively `lab ci artifacts origin master:myjob`

Less sure on what to do with https://docs.gitlab.com/ce/api/jobs.html#download-a-single-artifact-file -- which allows you to reach inside an archive and grab a specific file. I definitely want to support both tho!

Really just spitballin' here, the idea with `branch:job` was to emulate how git lets do stuff like `git checkout origin branch:file` -- A simple extension would just be to keep the colons going `lab ci artifacts origin master:myjob:path/to/my/file`, but mostly I'm wonder why colon separate at all and just do `lab ci artifacts [remote [ branch [ job [ path ]]]`

**Comment by jkleckner** [comment]
I found myself wanting this just today.

Something like `lab ci artifacts [remote [ branch [ job [ path ]]]` seems sensible.
