### ISSUE TITLE
Configuration docs

### ISSUE THREAD

**Issue by claytonrcarter** [zaquestion/lab#234]
As I was reading through the code, it seems like the configuration docs in the readme are getting a little outdated. I'm not familiar with Go, but does this capture the current behavior of `lab`:

1. If the user has env variables `LAB_CORE_HOST`, `LAB_CORE_USER`, `LAB_CORE_TOKEN`, use these values.
2. If the user has env variables `CI_PROJECT_URL`, `CI_REGISTRY_USER`, `CI_JOB_TOKEN`, use these values.
3. If the user has a `./lab.hcl`, read values from this file
4. If the user has a `~/.config/lab.hcl`, read values from this file
5. Finally, ask the user for values and save them in `~/.config/lab.hcl`

**Comment by zaquestion** [comment]
@claytoncarter That looks correct to me. One small note if you end up updating the docs, the second item should read something like "if lab is running in GitLab CI" since that's the purpose there.

**Comment by claytonrcarter** [comment]
Got it. Thanks! I'll try to work up a small PR sometime soon.
