### ISSUE TITLE
lab ci wait

### ISSUE THREAD

**Issue by temp** [zaquestion/lab#240]
I don't know wether or not this is possible, but it would be nice to have a ci command that simpy waits for the current pipeline to finish and then exits with status code 0 for success, and 1 for failure.
This would allow scripting of several pipelines that need to be run in a specific order. I know you can trigger builds inside a pipeline, but we need it the other way - like a listener.

This would allow something like this:
```
cd /whatever/docker-base
lab ci create
lab ci wait
cd /whatever/docker-project-that-uses-docker-base
# or maybe
lab ci create --wait
cd /whatever/another-docker-project-that-uses-docker-base
# or maybe
lab ci create
lab ci trace --exit-on-finish
...
```

**Comment by zaquestion** [comment]
I'm pretty sure we can pull this off! Thanks for including your usecase as well, that goes a long way in integrating your idea into lab as a whole and provide a tangible workflow to justify implementation.

That said, have you looked at multi-project pipelines in GitLab? This may fit your usecase more elegantly that the feature would?? https://docs.gitlab.com/ee/ci/multi_project_pipelines.html -- Let me know!

**Comment by temp** [comment]
Yes, I looked at multi project pipelines, but they don't support our use case.
We don't need a trigger from upstream, but a listen from downstream.
Like in my example a base docker image.
Now for example 10 projects use this base docker image, and every time the base docker image is built, I want the 10 project docker images to be rebuild. But I don't want to add trigger code for each project in the base docker repository...

**Comment by zaquestion** [comment]
@temp `lab ci status --wait` was added in `0.15.0` please let me know if this works for your purpose and reopen if needed.

**Comment by temp** [comment]
Looking good!
Maybe the spam-factor can be reduced by waiting a second between status-check while --wait'ing? Or add something like --quiet?

**Comment by temp** [comment]
Ah, some weirdness remains ;-)
I have a status --wait running, and it's still printing running messages, but a status on a second console reveals:

```
± lab ci status
Stage:   Name              - Status
...
Pipeline Status: failed
```

Maybe the wait is already done, but he's still busy printing?

**Comment by temp** [comment]
Wow, it kept running, and Mac OS just complained about no app memory left... 
Here's what it said:
![bildschirmfoto 2019-02-11 um 11 34 24](https://user-images.githubusercontent.com/216128/52557906-21dcd680-2df1-11e9-8e76-0f59be9a9550.png)
:-D

**Comment by zaquestion** [comment]
Oh my!

**Comment by zaquestion** [comment]
@temp Not sure what you may have ran into, but at least in my own usage of this:

```
lab ci trigger some/other/project ...
lab ci status --wait # no way to actually specify project.
```
Going to fix that, have you been able to gather any more info on what you may have ran into? Is it possible that you also needed to specify a separate pipeline?

**Comment by temp** [comment]
@zaquestion I started it from within my git-directory - then you don't need to specifiy the project!
And then the described behaviour occurs.

**Comment by zaquestion** [comment]
Ah, nice work around! I'll add the additional means as well soon

**Comment by claytonrcarter** [comment]
I've also encountered this. `lab ci status --wait` doesn't ever seem to return. As I read the code (you know my Go ain't great), it looks like it never actually retrieves an updated list of CI jobs and just loops over the first list it received ... which makes sense why it would never update! :)

**Comment by zaquestion** [comment]
Yep @claytonrcarter is right, my code was just bunk 😊

**Comment by bmeneguele** [comment]
@temp not sure if it's still a problem for you, but it should've been fixed with PR #361.
Please, feel free to let me know if it's not solved or if any other issue appear.

**Comment by temp** [comment]
@bmeneguele works fine now! 👍 
it would be awesome to be able to specify the wait-seconds, but this is really nice-to-have... ;-)

**Comment by bmeneguele** [comment]
> @bmeneguele works fine now! 👍

I'm glad to hear that :)

> it would be awesome to be able to specify the wait-seconds, but this is really nice-to-have... ;-)

Hmm... a timeout behavior? That's something to think about indeed.
Why don't you open a new issue with this suggestion so we can check it more "formally"?
It should be easy to make it happen.

**Comment by temp** [comment]
> Hmm... a timeout behavior? That's something to think about indeed.

Oh, no, I meant the wait time between 2 polls. Have seen the 1-second-wait in the sources. But for long running pipelines it would be ok to poll 5-15 seconds, to avoid hammering. Like I said, it's only a nice to have.

**Comment by temp** [comment]
Here is the snippet:

```go
// don't spam the api TOO much
time.Sleep(1 * time.Second)
```

**Comment by claytonrcarter** [comment]
Yup, when I fixed this feature, I picked 1s out of thin air! Adding a flag to configure the polling interval would be a trivial change; a great first issue/PR.

**Comment by bmeneguele** [comment]
Ahh, got it!
Yes! for sure it would be a really nice "first issue".
