### ISSUE TITLE
Show MR assigned to self

### ISSUE THREAD

**Issue by kuahyeow** [zaquestion/lab#249]
Is it possible to have an option to show MRs assigned to self ?

e.g. `lab mr list --mine`

**Comment by claytonrcarter** [comment]
The API supports this, and it probably wouldn't be too hard to implement. Basically, when we send off the API request, we would set the `AssigneeID` to the users ID. Could also be relevant for listing issues which are assigned to self.

@zaquestion I could take a whack at this if you like it, it's definitely w/i the scope of my modest skill set.

**Comment by zaquestion** [comment]
Yes!

**Comment by alexkalderimis** [comment]
I have implemented this in #319 , if anyone is interested in taking a look.
