### ISSUE TITLE
Install to user space

### ISSUE THREAD

**Issue by tfurf** [zaquestion/lab#262]
The install script installs into a system bin directory. Would it be acceptable to propose a PR to allow some user configuration here?

The use case is basically that there are users that might not have `sudo` privileges on their machine to install into `/usr/local/bin`, while it is perfectly acceptable to install to `~/.local/bin` (via CLI argument to `install.sh`).

**Comment by 1ace** [comment]
@tfurf #263 provides a solution for you; for your use-case you'd call it via `PREFIX=~/.local install.sh` :)
