### ISSUE TITLE
Liberapay: I want to give $1/month but account recipient not ready to receive new payments

### ISSUE THREAD

**Issue by maelvalais** [zaquestion/lab#267]
Dear @zaquestion,

I wanted to thank you for `lab`. It is so nice and useful that I wanted to donate so that your work gets rewarded. I know it is not that much, but I wanted to give $0.25 per week. For some reason, Liberapay says I cannot donate:
![liberapay](https://user-images.githubusercontent.com/2195781/50072520-c538b300-01d5-11e9-99e6-385e97c33df9.PNG)

**Comment by MartinDelille** [comment]
@zaquestion I would advice to connect both stripe and paypal account:
- stripe has lower fees
- paypal has more users

**Comment by zaquestion** [comment]
Oh my, and here I thought that's was all setup.

**Comment by zaquestion** [comment]
Okay! I think I got it, thanks so much @MartinDelille -- I've also decided all donation will go straight to my farm (because thats my stripe account) and making lab great of course but thats a given. If you're ever in Seattle say hello and I'll give you some free greens :D https://www.tight5.farm/

**Comment by MartinDelille** [comment]
Turning lines of code into food! The future is now! ;-)

**Comment by maelvalais** [comment]
Awesome, I'm both helping a developer AND the planet! ❤️❤️

**Comment by maelvls** [comment]
Hi!

Now that Github has a sponsorship program, do you wish to enroll? Right now, Github matches the donated amount, so it is even better 😀 It also means more visibilty as your project will appear on peoples profiles.

https://help.github.com/en/articles/sponsoring-a-developer

**Comment by zaquestion** [comment]
@maelvls I signed up for the beta, but haven't seen anything come through yet... Perhaps theres just a setting I need to find?

**Comment by zaquestion** [comment]
Yeah I'm still on the waitlist, will defs update here when I get in :D Thanks for all the support! Also just FYI will be a bit less available this week (getting married), and later in month ("minimoon")

**Comment by maelvls** [comment]
Congratulations!!! 🎉🎉🎉 I'm also going through many life changes right now, I feel you 😁

I went to one of my githubs projects settings and this button appears:

<img width="711" alt="Capture d’écran 2019-06-11 à 07 30 32" src="https://user-images.githubusercontent.com/2195781/59245895-d1e51380-8c1a-11e9-8d25-d2d65eeaeac9.png">

**Comment by zaquestion** [comment]
![notinbeta](https://user-images.githubusercontent.com/2358914/59304600-6bc5b400-8c4d-11e9-85d0-697f45a0e674.png)

Looks like that setting lets you reference different funding platforms, including GitHub's if you're in it. So I got an error listing my user for the sponsorship, but was able to get the button up and at least reference the liberapay

**Comment by maelvls** [comment]
Hi @zaquestion!
Did Github let you into the sponsor beta program yet? 😁

**Comment by zaquestion** [comment]
@maelvls ha! Your spidey senses must be working, I just got in a few days ago, it's on my list to get setup

**Comment by maelvls** [comment]
Yey!! I’m now sponsoring you through the GitHub Sponsor thing! 🥳

**Comment by zaquestion** [comment]
@maelvls deeply appreciate it, that donation goes directly to my farm. Which is struggling with the ongoing pandemic and farmers market shutdowns in Seattle. Every dollar counts, thanks for using and supporting `lab`
