### ISSUE TITLE
Unit tests do not pass on Windows

### ISSUE THREAD

**Issue by matthewdale** [zaquestion/lab#276]
Most common errors:
- > executable file not found in %PATH%
  - `lab_bin`
  - `vi`
  - `cp`
- > Expected nil, but got: &errors.errorString{s:"the key ... is not found"}
- path separator mismatch

I'd like to contribute to lab, but the inability to run the unit tests on Windows is blocking me from contributing.

**Comment by matthewdale** [comment]
Did this out-of-order, but figured I should create an issue anyway 😆 . Should be resolved with https://github.com/zaquestion/lab/pull/275.

**Comment by zaquestion** [comment]
Looking forward to more contributions :D
