### ISSUE TITLE
`git lab mr show` should be able to show the actual MR

### ISSUE THREAD

**Issue by 1ace** [zaquestion/lab#277]
Right now `git lab mr show` only shows a summary with the MR title and description, and a couple meta-data, but not the content of the MR.

It would make it much more useful if there was an additional flag (say `-p, --patch` for instance) that would fetch the branch and show it the way `git show ..$remote/$branch` does.  
(Bonus point for supporting `--reverse` or even making it the default, because the "anti-chronological order by default" of `git show` annoys me.)

**Comment by zaquestion** [comment]
Definitely something we want to support!

**Comment by MartinDelille** [comment]
Detecting the current merge request is done in the `lab mr browse` command. We should factorize the code.
