### ISSUE TITLE
panic when lab ci view loses connectivity to gitlab server

### ISSUE THREAD

**Issue by aboyett** [zaquestion/lab#285]
Connectivity was lost to the gitlab server while tracing a build job through `lab ci view`. `lab` threw a panic and left them terminal in an inconsistent state requiring `reset` to fix the terminal.

Ideally `lab` would handle the failure and attempt to reconnect, but at minimum I would hope that it exits gracefully restoring the terminal rather than panicking.

The stack trace below corresponds to the following line of code: https://github.com/zaquestion/lab/blob/bb7113ba86face26b8a7f78b08b99b8a1bef3c15/cmd/ci_trace.go#L96

I hope the stacktrace is readable enough, I had to reformat it as the panic was displayed over the corrupted display of the `lab ci view` output that triggered the panic.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e7f19]
                                                                                              
goroutine 69 [running]:
io/ioutil.readAll.func1(0xc0004cddb0)
    /usr/lib/go-1.11/src/io/ioutil/ioutil.go:30 +0x105
panic(0x972b40, 0xe3d1c0)
    /usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
bytes.(*Buffer).ReadFrom(0xc0003d6070, 0x0, 0x0, 0x0, 0x0, 0 x0)
    /usr/lib/go-1.11/src/bytes/buffer.go:206 +0x89                                        
io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/lib/go-1.11/src/io/ioutil/ioutil.go:36 +0xb5                     
io/ioutil.ReadAll(0x0, 0x0, 0xc0001e6046, 0xf, 0xc000310660, 0x9, 0x0)
    /usr/lib/go-1.11/src/io/ioutil/ioutil.go:45 +0x3e
github.com/zaquestion/lab/cmd.doTrace(0xaadb60, 0xc0000220e8, 0x7f91c09ad620, 0xc00 01f20c0, 0x93bae0, 0xc000334110, 0xc0001e6046, 0xf, 0xc000310660, 0x9, ...)
    /go/src/github.com/zaquestion/lab/cmd/ci_trace.go:96 +0x31d
github.com/zaquestion/lab/cmd.jobsView.func1.1(0xc000193790, 0xc000118380)
    /go/src/github.com/zaquestion/lab/cmd/ci_view.go:326 +0x204
created by github.com/zaquestion/lab/cmd.jobsView.func1
    /go/src/github.com/zaquestion/lab/cmd/ci_view.go:325 +0x117e
```

**Comment by zaquestion** [comment]
Sorry it was hard to plug all the holes where things can go horribly wrong, the stacktrace should help I'll try to get this fixed over the weekend
