### ISSUE TITLE
"lab issue close" deletes the issue

### ISSUE THREAD

**Issue by BrainBlasted** [zaquestion/lab#288]
Found this while closing an issue and then going to check off it's tasks. Going to the URL lead to a 404, and checking the issues list showed that is was gone rather than filed as Closed.

**Comment by zaquestion** [comment]
@BrainBlasted Looks like I didn't understand how to properly close issues when I wrote that. I've put up #289 to address the issue. Will release as `0.15.1` shortly

**Comment by zaquestion** [comment]
Released! Thanks for the tip!

**Comment by BrainBlasted** [comment]
Thanks for the quick fix!
