### ISSUE TITLE
Show ssh url on project creation

### ISSUE THREAD

**Issue by varac** [zaquestion/lab#303]
Currentliy, only the https url is shown on project creation:

```
 ~ $ lab project create dockerfiles 
https://.../varac/dockerfiles
```

It would be nice to also show the ssh URL so a git remote can easily configured.

**Comment by zaquestion** [comment]
@varac Creating the project will automatically add the ssh URL as a configured remote. Is that suitable for your purposes?

**Comment by varac** [comment]
Oh, I wasn't aware of this, awesome!
