### ISSUE TITLE
Support Custom Main Branch Names

### ISSUE THREAD

**Issue by BrainBlasted** [zaquestion/lab#304]
GitLab allows users to choose the main branch name. Some projects are using things like mainline or develop instead of master. `lab` always assumes that master exists, and will by default initiate MRs against `origin/master`.

**Comment by towo** [comment]
This could be pulled from a lab-specific git setting (e.g. `lab.merge-target`) to allow integration with native configuration, or could be queried from GitLab via the API (attribute `default`  is `true` when quering `repository/branches`).

**Comment by brettdh** [comment]
I got bitten by this today - my project has a `master` branch, but the default branch is different, and we almost always open MRs in the web UI against the default branch.

**Comment by zaquestion** [comment]
I believe this should be resolved once https://github.com/zaquestion/lab/pull/391 releases

**Comment by zaquestion** [comment]
Support can be improved by updating this logic for determining the forking scheme: https://github.com/zaquestion/lab/blob/4ebb574d55311e8d8497c48d18eacc98110f8b24/cmd/root.go#L247

**Comment by prarit** [comment]
I think we can safely close this given the changes in #391 .
