### ISSUE TITLE
CI job allowed to fail 

### ISSUE THREAD

**Issue by ejiek** [zaquestion/lab#308]
It's possible to have failed jobs which don't block pipeline.

In gitlab interface they are marked with yellow exclamation mark.
In `lab ci view` they are shown same as regular failed jobs

Reason is gitlab API which shows them as  failed and there is no any other sign of being allowed to fail.

I think it's would be handy to see the difference.

WDYT is it a good idea to parse `.gitlab-ci.yml` to find out if job is allowed to fail?

_____
PS. We can try requesting it from Gitlab API =]

**Comment by zaquestion** [comment]
The above should be the place to request it. To parse the `.gitlab-ci.yml` I've used just a standard yaml parser before I don't think it would be too bad to implement what you're looking for.

**Comment by ejiek** [comment]
Thanks for the response!

I'll create PR when ready.

P.S. I'm a bit afraid that we have `.gitlab-ci` only for current local brunch.
