### ISSUE TITLE
lab ci trigger 404 not found response

### ISSUE THREAD

**Issue by huhuta** [zaquestion/lab#309]
```
$ lab ci trigger
2019/05/15 10:52:37 ci_run.go:79: POST https://gitlab.com/api/v4/projects/mygroup/myproject/trigger/pipeline: 404 {message: 404 Not Found}
```

**Comment by zaquestion** [comment]
Hey, this isn't enough for me to act on, if you have a bit more context might be able to help you out.

- Does the tool otherwise work? Can you perform `lab mr list`? 
- Are you sure there is ci on the branch you are trying to trigger on?
- Did you mean to use `lab ci create`?

**Comment by huhuta** [comment]
Sorry I was confused with ``` lab ci create```
thanks
