### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#31]

**Comment by zaquestion** [comment]
![zaqlogo](https://user-images.githubusercontent.com/2358914/33514153-78e887f8-d703-11e7-91d4-458f52656106.png)

**Comment by zaquestion** [comment]
Git Logo page with link to license: https://git-scm.com/downloads/logos
GitLab Logo use guidelines: https://gitlab.com/gitlab-com/gitlab-artwork/blob/master/README.md

**Comment by zaquestion** [comment]
![gopher_logo_orange_brown](https://user-images.githubusercontent.com/2358914/33514164-d2bd7ebe-d703-11e7-864c-b776223cc0f3.png)

**Comment by zaquestion** [comment]
Idea for banner:
![lab_banner](https://user-images.githubusercontent.com/2358914/34196973-420d389a-e519-11e7-92e6-3a1486d6b280.png)

**Comment by jnv** [comment]
I really like the Gopher-y pixelart logo!

**Comment by zaquestion** [comment]
@jnv Its likely to be the one! It sounds like @nkprince007 wants to put a horse in race. Lets tentatively say I'll make an official decision early January

**Comment by Arreity** [comment]
![gopher_logo_orange_brown](https://user-images.githubusercontent.com/3167497/34473826-40b4987c-ef2c-11e7-90b9-5ff322c4966f.png)
Here is a version with transparent background.

**Comment by zaquestion** [comment]
Opened https://gitlab.com/gitlab-com/www-gitlab-com/merge_requests/9219 to use the gopher logo. Also added the banner the readme in 40d40251834b8dc377fcb94ebba789ba72acfbc9

**Comment by zaquestion** [comment]
The logo is live on: https://about.gitlab.com/applications/#cli-clients
