### ISSUE TITLE
List all issues assigned to me

### ISSUE THREAD

**Issue by jtbairdsr** [zaquestion/lab#315]
I would like to be able to see my todo list at the cli.  I can filter them by label but I can't find a way to filter them by assignee...

**Comment by claytonrcarter** [comment]
This is related to #249, and also shouldn't be too difficult. The API definitely supports it: https://docs.gitlab.com/ce/api/issues.html#list-project-issues (See `assignee_id` and `assignee_username`.)

**Comment by zaquestion** [comment]
`scope=assigned_to_me` will work, hmm thought we had this already even

**Comment by prarit** [comment]
This functionality exists in the latest git tree.

`
lab mr list --mine`

or
`
lab mr list --assignee prarit`
