### ISSUE TITLE
Add label delete command

### ISSUE THREAD

**Issue by flaub** [zaquestion/lab#316]
I'm using this excellent tool in a larger code repository automation tool. I'm using the ability to label MRs as a way of tracking which MRs go to which branches locally. This all works great, except that there's currently no way to remove unused labels once the MRs have been merged.

There appears to be an API that would do the trick:
https://docs.gitlab.com/ce/api/labels.html#delete-a-label

**Comment by prarit** [comment]
@flaub , I know this is a very late response.  This functionality exists in the current lab git tree as  

`
lab mr edit <mr_id> --label <label_name>`

and
`
lab mr edit <mr_id> --unlabel <label_name>`
