### ISSUE TITLE
Allow generating completion without needing to auth or configure

### ISSUE THREAD

**Issue by maxice8** [zaquestion/lab#321]
I'm trying to package lab for Alpine Linux and i want to generate the completion on the fly as the package is built.

**Comment by zaquestion** [comment]
I've put in a hacky allowance for this, since unfortunately I didn't make it easy to circumvent the config loading/auth path, but it should allow for this case no problem.

Ref: https://github.com/zaquestion/lab/pull/323

**Comment by maxice8** [comment]
Thank you very much, although i believe the optimal state is like `hub` where it only does auth if you do an operation that requires it, lab has this ruby-like delay when it starts that makes it very annoying to script.

**Comment by maxice8** [comment]
wfm

**Comment by zaquestion** [comment]
Yeah that's something I'm hoping to address in this release as well thats called out in https://github.com/zaquestion/lab/issues/292
