### ISSUE TITLE
lab project create - failing to create project

### ISSUE THREAD

**Issue by colonelrascals** [zaquestion/lab#329]
When I run the command `lab project create` I get the following error message:

`project_create.go:67: POST https://gitlab.com/api/v4/projects: 400 {message: {limit_reached: []}, {visibility_level: [internal has been restricted by your GitLab administrator]}}`

I have no restrictions set as this is a personal account.

**Comment by zaquestion** [comment]
We're seeing this in out tests as well, I suspect something changed on GitLab side, will take a look.

**Comment by colonelrascals** [comment]
It may be worth noting that if the project already exists there is no issue. This only seems to happen on `project create`

**Comment by zaquestion** [comment]
@deconstructionalism Does is work if you use the `--public` or `--private` flag? I'm wondering if GitLab.com just doesn't support internal anymore

**Comment by zaquestion** [comment]
![no_internal](https://user-images.githubusercontent.com/2358914/63896920-710ee100-c9a8-11e9-9e63-b5828583ace9.png)
It looks like it's gone from there create pages.

**Comment by claytonrcarter** [comment]
FWIW, it's still included in their API documentation at https://docs.gitlab.com/ee/api/projects.html

![Screen Shot 2019-08-28 at 7 25 22 PM](https://user-images.githubusercontent.com/1420419/63899154-c7d8e280-c9c9-11e9-8d2d-f3db147378c7.png)

**Comment by claytonrcarter** [comment]
Nevermind: https://docs.gitlab.com/ee/public_access/public_access.html#internal-projects

![Screen Shot 2019-08-28 at 7 28 10 PM](https://user-images.githubusercontent.com/1420419/63899224-16867c80-c9ca-11e9-9ab6-ecd4b2ffc040.png)

**Comment by claytonrcarter** [comment]
I'm closing this b/c `lab`s default project visibility was changed to "private" in 284fbb8
