### ISSUE TITLE
Backup ISSUE_EDITMSG in case of failure

### ISSUE THREAD

**Issue by claytonrcarter** [zaquestion/lab#332]
For one reason or another, I find that `lab issue create` fails (or `issue note`, etc) and my lovingly crafted title and description have to be recreated from scratch. Which is frustrating. 

My proposal:

1. Before `lab` drops out to an `$EDITOR`, it should check if there is a backup file w/ a name that matches the file it's about to edit. (eg if we're about to edit `ISSUE_EDITMSG`, thenwe should check if there's an `ISSUE_EDITMSG.bak` file lying around.)
2. If we find such a backup, ask the user if they want to use the backup file or discard it and start fresh.
3. Do whatever the user says.
4. When `$EDITOR` returns and `lab` regains control, we should create a backup of the temp file that was just edited before we check/validate/sanitize the contents and submit it to GL.
5. If the check/validate fails, or the submission to GL returns a failure, then we act as we do now for errors and leave the backup file as is.
6. If the request to GL returns successful, then we should act as we do now for successes except that we should also delete the backup file.

Thanks!

**Comment by zaquestion** [comment]
I would have thought this worked, and I believe I've seen that in action, but I don't recall the case myself. I believe lab tests to "open or create" it's edit file and only cleans up after getting the text it needed, otherwise it should be saved for next time. This and laziness was the reason for not creating back up files. But also, I could be full of it

**Comment by claytonrcarter** [comment]
Ah, thanks. I think I may have over-engineered my proposal. As I currently experience and read the code, the call to `defer os.Remove(filePath)` at https://github.com/zaquestion/lab/blob/master/internal/git/edit.go#L44 seems to be removing the editor file regardless of success or failure. I just played around with moving that down to line ~90 and I'm seeing what you describe: my botched issue is preserved and re-opened next time.

**Comment by claytonrcarter** [comment]
However, that only re-opens the file if ended up "empty" after removing comments. It doesn't address the case where the GL API rejects the submission.
