### ISSUE TITLE
Zsh completion doesn't show "repo" alias for "project"

### ISSUE THREAD

**Issue by forivall** [zaquestion/lab#333]
It looks like it was solved in the upstream (https://github.com/spf13/cobra/pull/669) but your version is pinned at `v0.0.0-20180412120829-615425954c3b` (I'm not a gopher, so i'm not 100% sure that that's the reason)

**Comment by zaquestion** [comment]
@rsteube Any reason we can't update to the latest cobra? I know we've had some back and forth about cobra versions and intricacies, I can't remember where we landed in the end.

**Comment by rsteube** [comment]
https://github.com/spf13/cobra/pull/884 is needed for the custom completions we used in `lab`.
Since that takes longer than i was hoping we can reopen #313 to update to the newest cobra.

**Comment by rsteube** [comment]
btw. the change in mentioned PR seems to concern just the bash completion and not zsh so that might eventually still be missing in the new version (at least i don't see any mention of `alias` in https://github.com/spf13/cobra/blob/master/zsh_completions.go) .

**Comment by zaquestion** [comment]
Thanks for the refresher, I've poked the maintainers on https://github.com/spf13/cobra/pull/884 -- that said sounds like updating cobra won't actually add aliases for zsh, still I wouldn't mind having the functionality for bash :D
