### ISSUE TITLE
git remote bug when manually forking a repo

### ISSUE THREAD

**Issue by jackmac92** [zaquestion/lab#335]
Given the following steps:
1. Clone some existing repo locally
2. git remote rename origin upstream
3. git remote add origin $NEW_REMOTE

I'm running into a bug where the incorrect remote is used for commands like `lab ci view` and `lab repo browse`. It uses what is now the `upstream` remote, when I want it to use `origin`.

Detail that seems interesting to me
To debug the issue I removed all remotes from the local repo, and added them back individually. When I add the NEW_REMOTE as origin, `lab` commands work as expected. However, re-adding the upstream remote breaks it again

**Comment by zaquestion** [comment]
Yeah `upstream` gets special behavior in lab. When the `upstream` repo exists lab defaults to that over `origin` for certain commands. Lab attempts to pick the "forked" remote or "forkedFrom" remote based on what it thinks is most likely for that command. 

For most commands like `lab repo browse` lab expects you'll want to browse the "forkedFrom" repo as its the source of truth, similar for listing issues or creating merge requests. This behavior can be overridden by passing in the remote you wish to operate on (almost always the first argument to the command)

`lab ci view` works a little differently (like some other commands and like `lab mr create` does to determine where to look for the source branch). You can control this by setting the upstream on the branch when you push it `git push -u origin branch`, then when `lab ci view` operates on it it will use that remote.

There might be a little bit more to it than that, but hope this helps!

**Comment by bmeneguele** [comment]
It seems it wasn't an issue per se.
I'm closing it. Feel free to reopen if needed.
