### ISSUE TITLE
build error: `undefined: os.UserHomeDir`

### ISSUE THREAD

**Issue by gimbar** [zaquestion/lab#336]
Lab doesn't build if go 1.11 is used.
os.UserHomeDir is a function from go version 1.12.
https://github.com/zaquestion/lab/blob/master/README.md claims only "1.11+" is needed.

**Comment by zaquestion** [comment]
I believe that, I'll get the readme updated

**Comment by zaquestion** [comment]
Updated readme to clarify go version requirements
