### ISSUE TITLE
Install script is not Posix

### ISSUE THREAD

**Issue by soullivaneuh** [zaquestion/lab#339]
Two problems here:

- The script is dependent to bash. Make it compatible with sh would simplify the installation process on tiny os. Useful for Docker application
- The `--only` grep option does not exist on all grep binaries.

**Comment by zaquestion** [comment]
Yeah that all seems reasonable to me, when I wrote it it seemed like bash was enough of a given that there wouldn't be issues, but it's since borked. I haven't had a lot of time to circle back to some of this, but pull requests would be reviewed and likely merged if they addressed these concerns.
