### ISSUE TITLE
Create Homebrew Formula

### ISSUE THREAD

**Issue by jnv** [zaquestion/lab#34]
Hi, I'd like to create a Homebrew formula for this project, but it seems there are no [releases or tags](https://github.com/zaquestion/lab/releases), so I cannot point to a stable version. Do you think you could add tags as part of your release process? Thanks!

**Comment by zaquestion** [comment]
Wow, I'd love a homebrew formula! I'll tag the last release in the next hour or so.

**Comment by jnv** [comment]
Excellent, thank you! :smile: This my WIP formula which seems to work nicely, so far. I plan to finish it on Sunday, but feel free to pick it up if you have chance to finish it sooner:

```rb
class Lab < Formula
  desc "A hub-like tool for GitLab"
  homepage "https://github.com/zaquestion/lab"
  url "https://github.com/zaquestion/lab.git",
      :revision => "5d3f274fbf89dfe8a4de3a26eb19a8a639df2f93"
  head "https://github.com/zaquestion/lab.git"
  version "0.5.0"
 
  depends_on "go" => :build
  depends_on "dep" => :build
  
  def install
    ENV["GOPATH"] = buildpath
    path = buildpath/"src/github.com/zaquestion/lab"
    path.install buildpath.children
    cd path do
      system "dep", "ensure"
      system "go", "build", "-o", bin/"lab"
      bin.install Dir["bin/*"]
      prefix.install_metafiles
    end
  end

  test do
    #assert_match version.to_s, shell_output("#{bin}/lab -v")
  end
end
```

**Comment by zaquestion** [comment]
@jnv I've tagged `v0.5.0`: https://github.com/zaquestion/lab/releases/tag/v0.5.0

**Comment by jnv** [comment]
I have finished the formula, however `brew audit` states: `GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)`. I'd wait a bit before submitting this to homebrew-core, but it is easy to maintain an independent tap.

I have created this repo: https://github.com/jnv/homebrew-tap
From here you can install lab with `brew install jnv/tap/lab`

I think a step further would be to synchronize the tap with further releases and add binary bottles. I don't have much experience with Go, but I think [goreleaser](https://goreleaser.com/) can help. It builds binaries, create GitHub releases for tags and also pushes updates to a separate tap repository. If you agree with this, I will look into goreleaser integration with Travis.  I also recommend forking-off my tap, so you can push updates to it from CI under your token.

**Comment by zaquestion** [comment]
@jnv Thanks for looking into this! It all seems very agreeable. With a means to install with Bree there's just a few things I want to sort out and Ill start sharing this around a bit more. Hopefully this should net the stars and forks we need

**Comment by zaquestion** [comment]
@jnv Per your recommendation I've created https://github.com/zaquestion/homebrew-tap -- I kept your commit intact although did not use a fork-parent relation for it in the likely event I put more brew scripts there.

**Comment by zaquestion** [comment]
@jnv Were you able to successfully install with brew? I'm getting
```
$ brew install zaquestion/tap/lab
==> Installing lab from zaquestion/tap
Error: No available formula with the name "dep" (dependency of zaquestion/tap/lab)
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
dependency-check          depqbf                    godep                     homebrew/php/deployer     homebrew/php/pdepend      ios-deploy                makedepend
To install one of them, run (for example):
  brew install dependency-check
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by zaquestion** [comment]
https://github.com/zaquestion/lab/pull/37 -- https://github.com/zaquestion/homebrew-tap/blob/master/lab.rb
