### ISSUE TITLE
lab does not set the username in lab.hcl at first run

### ISSUE THREAD

**Issue by paride** [zaquestion/lab#342]
The README.md mentions that at first run lab should ask for the user's GitLab username:
```
$ lab
Enter default GitLab host (default: https://gitlab.com):
Enter default GitLab user: zaq
Enter default GitLab token:
```
but I'm not getting asked the "user" question and indeed the generated `lab.hcl` has a blank line between the `host` and `token` lines:
```
"core" = {
  "host" = "https://gitlab.com"

  "token" = "XXX"
}
```

Nit: last line of the generated `lab.hcl` file does not end with a newline, as it should be definition of "text file".

**Comment by paride** [comment]
Then I guess the mention of `LAB_CORE_USER` in `README.md` should be removed too, which is what actually made me think the username still had to be set.

**Comment by zaquestion** [comment]
Fixed in https://github.com/zaquestion/lab/commit/3680ee25f1255c2aa643c947ed0089e7458bd2b1
