### ISSUE TITLE
hub/lab command priority

### ISSUE THREAD

**Issue by paride** [zaquestion/lab#343]
It seems that some commands are provided by both lab and hub. e.g.  `fork` and `issue`. What's their priority? If I `lab fork` a project, will `lab` check if it is possible to fork it in GitLab, and fallback to GitHub if it isn't?

In general I find this a bit confusing, and I'd prefer to disable the `hub` integration completely. Even if the behavior is simple and well defined, e.g. GitLab always has precedence, I don't think offering a crippled `hub` frontend is the best thing to do. Is it possible to completely disable the `hub` integration?

Thanks!

**Comment by zaquestion** [comment]
Removing it entirely is a task for `1.0` and I have that code on a branch as well. I don't think there's a way to disable it without a code change (or not having hub in the path atm, but easy to add one)

The hub integration was meant to allow the use of hub and lab when aliased as git, but there are better ways for it. If you don't mind compiling lab, I'd just remove the logic in `internal/git/git.go` for selecting hub its a couple lines

**Comment by paride** [comment]
Thanks @zaquestion, looking forward to the 1.0 release then!

**Comment by bmeneguele** [comment]
With #605 merged, this issue is now fixed.

**Comment by paride** [comment]
@bmeneguele time to update the project description? It still says:
> Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab

**Comment by bmeneguele** [comment]
@paride ooh! of course!
I changed it in README and forgot the description. Many thanks for the heads up!

@zaquestion could you change that? You're the project owner and the only one allowed to change that :)
