### ISSUE TITLE
lab fork should allow to specify the protocol

### ISSUE THREAD

**Issue by mfriedenhagen** [zaquestion/lab#345]
* Right now `lab` seems to default to using `ssh` when forking stuff.
* Using `ssh` is not possible in our internal instance.
* `lab` uses an API token anyways to do stuff, so the only "known, good way" to reach the GitLab instance is https anyways.

My suggestion would be to default to use `https` and make `ssh` an option.

**Comment by eedgar** [comment]
We also have the same issue.

**Comment by eedgar** [comment]
https://github.com/zaquestion/lab/pull/477

**Comment by bmeneguele** [comment]
It's now solved.
However, the default protocol still is SSH. For using HTTP call the command with `--http`.
