### ISSUE TITLE
lab fork should detect existing fork

### ISSUE THREAD

**Issue by nijel** [zaquestion/lab#347]
With `hub fork` when there is existing fork, it is added as remote. With `lab fork` it fails with `{message: {name: [has already been taken]}, {path: [has already been taken]}}`. I'd expect that both tools behave similarly in such situation.

Related `hub` code is here: https://github.com/github/hub/blob/03533a167e09c53323b892c38e3257bdfdb47a6d/commands/fork.go#L75-L99

To reproduce, clone a repo, execute `lab fork`, clone it in different location (or on different system) and execute `lab fork` again.

**Comment by nijel** [comment]
Hmm, now I can not reproduce this again. Looks like the issue was actually in conflicting names.

**Comment by zaquestion** [comment]
hmmm, well thats comforting. I know it didn't do that when I first wrote it, but the gitlab api changes, so it's not infeasible there was a regression here

**Comment by bmeneguele** [comment]
Closing issue based on the feedback and issue date.
