### ISSUE TITLE
Allow specifying multiple assignees with `lab mr create`

### ISSUE THREAD

**Issue by AlecBenzer** [zaquestion/lab#349]
As-is, it seems only one assignee can be specified via the CLI.

```bash
# Seems to try to assign to someone named "foo,bar", which can't be found and so no assignee is set.
$ lab mr create -a foo,bar

# Only the last assignee (bar) is respected.
$ lab mr create -a foo -a bar
```

**Comment by zaquestion** [comment]
That's correct, `lab mr create` would appear to still use the old implementation. This shouldn't be too hard to implement 

https://github.com/zaquestion/lab/blob/master/cmd/mr_create.go#L34 the flag should be updated to use a slice like the adjacent flags

https://github.com/zaquestion/lab/blob/master/cmd/mr_create.go#L162 needs to be updated to use `AssigneeIDs` (vs `AssigneeID`)
- should be set to an `assigneeIDs` slice by looping over `assignees` and calling `getAssigneeID`

I'll flag for the next milestone and if someone wants to implement I can review and get a patch release out for this rather quickly
