### ISSUE TITLE
Proposal: Alias `lab mr ls` to `lab mr list`

### ISSUE THREAD

**Issue by adamryman** [zaquestion/lab#35]
I remembered that `lab` can checkout MR's and could list them as well.

Attempted `lab mr ls`. Which did not work. Though it did print out a nice help message which told me `lab mr list` had the desired functionality.

Thoughts on aliasing `lab mr ls` to `lab mr list`? 

I would be happy to submit a PR if the feature sounds good.

**Comment by zaquestion** [comment]
Very easy to do add
```
Aliases: []string{ls}
```
to https://github.com/zaquestion/lab/blob/master/cmd/issueList.go#L14 and
https://github.com/zaquestion/lab/blob/master/cmd/mrList.go#L14
