### ISSUE TITLE
lab ci view not responsive with lab 0.17.0

### ISSUE THREAD

**Issue by temp** [zaquestion/lab#356]
I'm using lab ci quite a lot, but with 0.17.0 `lab ci view` stopped working like expected.
It shows the current pipeline, but nothing is happening anymore. Arrow key don't move the selected job, pressing `q` or `ctrl-c` doesn't exit. And the view isn't updated, changes in the pipeline aren't reflected (e.g. job done).

**Comment by mfriedenhagen** [comment]
Same here on macOS 10.15.2 (19C57), I had to `killall lab` it.

**Comment by zaquestion** [comment]
The `tview` dep did get updated in this release https://github.com/zaquestion/lab/commit/edc559f3763cb6afbd98b4a13d08cc3edb9a55e0

**Comment by zaquestion** [comment]
@temp @mfriedenhagen can either of you confirm `0.17.1` fixes it on your side

**Comment by zaquestion** [comment]
@temp @mfriedenhagen can either of you confirm `0.17.1` fixes it on your side

**Comment by mfriedenhagen** [comment]
Hello @zaquestion , yes and no for me:
- the view mode reacts again and I can navigate and see the log 
- however in a Maven build all log lines are mostly empty
- I will create another issue for that one. 
- My guess would be this is because Maven prints the log level [INFO] in most lines
