### ISSUE TITLE
Add fish completions

### ISSUE THREAD

**Issue by andreiborisov** [zaquestion/lab#367]
Would be nice to provide `fish` shell completions in addition to `bash` and `zsh`

**Comment by rsteube** [comment]
I gave this try by adapting the zsh completion for fish and so far it looks pretty promising: https://github.com/rsteube/cobra-fish-gen/commit/b5ef2c3bc41f01dbf7449d0ba515a5df807d7ed6

Integrated it here as a test: https://github.com/rsteube/lab/tree/fish

related: #368

**Comment by rsteube** [comment]
Merged it into a new project and added bash as well: https://github.com/rsteube/carapace
