### ISSUE TITLE
mr merge fails if no CI pipelines exist

### ISSUE THREAD

**Issue by koberleitner-hpg** [zaquestion/lab#369]
I have the lab 0.17.2 CLI installed on macOS and mostly working well thus far with GitLab 12.3.1, however I'm having issues with the `mr merge` command. Running a merge, such as:

```
lab mr merge 3
```
fails with the error:
```
2020/03/09 13:17:08 mr_merge.go:29: PUT https://mycompanysgitserver.com/api/v4/projects/1594/merge_requests/3/merge: 405 {message: 405 Method Not Allowed}
```
I found that PUT `https://mycompanysgitserver.com/api/v4/projects/1594/merge_requests/3/merge` works fine via curl and Postman. After some digging though the project code, I see that `MergeWhenPipelineSucceeds = true` is set when merging any merge request.

I then tried a PUT which sets this flag per the [GitLab API docs](https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr), `https://mycompanysgitserver.com/api/v4/projects/1594/merge_requests/3/merge?merge_when_pipeline_succeeds=true` and I was able to reproduce the same HTTP 405 response. 

As best I can tell, there is no way to opt out of this setting which is an issue for a project that does not use pipelines.  I suppose a solution would be to make this option configurable via command switch?

**Comment by bmeneguele** [comment]
Hey, hi @koberleitner-hpg,

The option `-i` was introduced in v0.22.0. It wasn't made default to keep backwards compatibility with those already expecting a default "merge when pipeline succeeds".
```
$ lab mr merge --help
Merges an open merge request. If the pipeline in the project is
enabled and is still running for that specific MR, by default,
this command will sets the merge to only happen when the pipeline
succeeds.

Usage:
  lab mr merge [remote] <id> [flags]

Flags:
  -h, --help        help for merge
  -i, --immediate   merge immediately, regardless pipeline results
...
```
It should solve your case.
Feel free to reopen the issue if that's not the case.

Many thanks.
