### ISSUE TITLE
Is it possible list all issues from a given milestone? 

### ISSUE THREAD

**Issue by mmngreco** [zaquestion/lab#370]
Hi there,

I'm wondering if is possible list all issues from a given milestone. It would be very helpful if we could do something like the following:

```bash
lab issue --milestone my-milestone ls 
lab milestone ls
```

**Comment by fmuellner** [comment]
#549 added support for milestones, including the ability to filter issues/merge-requests by milestone.

**Comment by mmngreco** [comment]
Nice, that's amazing! 

It's present in the last release? if so, how can I use it ? I've update lab but I could'n find anything in the documentation.

**Comment by fmuellner** [comment]
No, it only landed after v0.18.0

**Comment by mmngreco** [comment]
I saw the new release of lab in github so I could try this argument and it works pretty well, thank you for your support!
