### ISSUE TITLE
[feature request] Create MR with title and description from a file

### ISSUE THREAD

**Issue by abeluck** [zaquestion/lab#373]
hub's pull-request supports the `-F` / `--file` option to create a PR from a prepared markdown file

I'm really missing this particular feature from lab, as I have a nice automation workflow where bots create nicely formatted MRs using this feature.

ref: https://hub.github.com/hub-pull-request.1.html

```
-F, --file FILE

    Read the pull request title and description from FILE. Pass "-" to read from standard input instead. See --message for the formatting rules
```

**Comment by zaquestion** [comment]
Seems reasonable, and I appreciate hearing the workflow you're looking for. lab is already working with files to read the title and description, so it should be relatively straightforward to add this flag. Would definitely consider a pull request.

**Comment by Madh93** [comment]
> Seems reasonable, and I appreciate hearing the workflow you're looking for. lab is already working with files to read the title and description, so it should be relatively straightforward to add this flag. Would definitely consider a pull request.

Is there an example of how to create a MR reading the title and description from a file?

**Comment by zaquestion** [comment]
https://github.com/zaquestion/lab/pull/400 added support for this
