### ISSUE TITLE
lab --version requires api authentication

### ISSUE THREAD

**Issue by nijel** [zaquestion/lab#374]
Invoking with simple args such as ``--version`` or ``--help`` should not require authentication to GitLab and should not query the remote server.

Without configuration:

```
lab --version
Enter GitLab host (default: https://gitlab.com): 
```

When hitting rate limiting on GitLab:

```
lab --version
2020/03/28 19:36:45 main.go:178: GET https://gitlab.com/api/v4/user: 429 failed to parse unknown error format
```

**Comment by prarit** [comment]
Looks like this was resolved in #421
