### ISSUE TITLE
StringSliceP vs. StringArrayP usage for flags

### ISSUE THREAD

**Issue by odise** [zaquestion/lab#376]
Hi,

I just came around an issue while adding notes to project issues like the one below:

```
lab issue note 1 -m "{\"key\": \"value\"}"
Error: invalid argument "{\"key\": \"value\"}" for "-m, --message" flag: parse error on line 1, column 3: bare " in non-quoted-field
```

After a bit of research I found that this is related to the usage of `pflags` StringSliceP parameter type used on various places in the code. Specifically `GetStringSlice` is raising the error above. 

I just would like to put https://github.com/spf13/pflag/issues/157 as a reference here and suggest using `StringArrayP` flag type at least for the issue command part. I'm unsure about the others which is the reason for raising the issue without a PR ready to solve it. 

Any thoughts from your end?

**Comment by zaquestion** [comment]
Interesting, at the moment I don't recall making a conscious choice to choose one over the other, and I'm thinking I probably thought they were alaises to the same functionality... 

Thanks for the reference issue, seeing the difference clearly, I think `StringArrayP` seems more appropriate for a lot of our stuff I imagine. Particularly the message flags. Things like assignees and labels SliceP seems more fitting. Just a gut take, PRs welcome, if we change the message flag would just like to see that be consistent across the various objects.

**Comment by prarit** [comment]
Since #431 was merged I think this can be closed.
