### ISSUE TITLE
lab can't handle signed commits with git set up to show the signature info

### ISSUE THREAD

**Issue by l29ah** [zaquestion/lab#379]
have following in `~/.gitconfig`:
```
[log]
	showSignature = true
```
then try to `lab mr create`
observe the merge request boilerplate being screwed up by the signature info
similar bug in `hub`: https://github.com/github/hub/issues/1379

**Comment by zaquestion** [comment]
@l29ah would the same solution they used on hub be suitable for ya? I'm not sure if simply overriding `showSignature` on the `git show` call is ideal?

**Comment by l29ah** [comment]
Yes it should be good.

**Comment by zaquestion** [comment]
This is already in place for `git.Log` https://github.com/zaquestion/lab/blame/master/internal/git/git.go#L102

Just need to add `"log.showSignature=false",` to https://github.com/zaquestion/lab/blame/master/internal/git/git.go#L91

**Comment by prarit** [comment]
@l29ah , could you try the latest tree?  I think this should be resolved as "log.showSignature=false" has been added to the internal git Log() function.

**Comment by prarit** [comment]
Closing for now.  @l29ah if you still have a problem please reopen this issue.
