### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by galan** [zaquestion/lab#410]
The last release is from December 2019 and I wanted to ask if there is a plan to release a new version?

I'm waiting for some features, such as https://github.com/zaquestion/lab/issues/349

Thanks for your efforts and this helpful tool!

**Comment by leipert** [comment]
Hey @galan, this is happening soon as part of: https://github.com/zaquestion/lab/issues/406

**Comment by galan** [comment]
Thanks, looking forward to it.
