### ISSUE TITLE
Config file overwritten if user is empty

### ISSUE THREAD

**Issue by bmeneguele** [zaquestion/lab#411]
Hi @zaquestion and @prarit,

In commit 1285411b8584bac827bf876e6c1d44180e871d5b @prarit forced the `core.user` config option to be written to the config file in case it's empty, however Viper doesn't update/merge the configuration file, but overwrites it: if you have a config file like the following one:
```
"core" = {
  "host" = "https://gitlab.com"
  "user" = ""
  "token" = "XXXXXXXXXXXXXX"
}
```
And you run `lab`, the code messes up with the config file:
```
"core" = {
  "user" = "bmeneg"
}
```
`viper.WriteConfigAs()` only writes those options that got `viper.Set()`'ed, all the others are not considered.

With that,
- should we really touch the config file from within the app without user's knowledge? Wouldn't it be better to warn the user to set the `core.user` option instead?

I know you guys are planning to overhaul the configuration stuff soon, but I think we should fix it regardless of the rework - unless you think it'll be released pretty soon :-D.

Another thing, this same behavior would be interesting to be seen in all other options: what happens if `core.user` is there but `core.host` and `core.token` aren't?
```
2020/09/01 18:47:07 main.go:92: <nil>
2020/09/01 18:47:07 main.go:93: missing config value core.host in /home/bmeneg/.config/lab.hcl
exit status 1
```
A suggestion I think would be nice is: 
- separate between which options are optional and which are required
  - if the config file exists, but some required options are missing: ask the user to enter it from stdin (like it's done when the config file doesn't exist.
  - if the config file exists, but some optional options are missing: do nothing.

What do you guys think?
I can help with getting it fixed while the you guys can focus on the overhaul.

**Comment by zaquestion** [comment]
In the short term, it might be easiest to just revert that commit. Originally user was in the config, but I removed it to make lab "smarter" and remove 1 less step for the user. That decision has caused more heartache than I would have hoped for...

In any case, ideally we'd lookup the user around https://github.com/zaquestion/lab/blob/master/main.go#L69 so it's written in when the config is created. I'm not sure why I didn't implement it that way in the first place, so it may be some doing to make that happen.

**Comment by prarit** [comment]
Ouch.  @bmeneguele, can you revert 1285411b8584 ("config: Fix missing core.user entry") locally and test?  If that works I'll revert ASAP.

I can reproduce this locally and reverting that commit seems to resolve the problem.  I will revert after you confirm.

**Comment by bmeneguele** [comment]
> Ouch. @bmeneguele, can you revert [1285411](https://github.com/zaquestion/lab/commit/1285411b8584bac827bf876e6c1d44180e871d5b) ("config: Fix missing core.user entry") locally and test? If that works I'll revert ASAP.
> 
> I can reproduce this locally and reverting that commit seems to resolve the problem. I will revert after you confirm.

Yes, reverting the patch solves the problem. You've my green light :D

> In any case, ideally we'd lookup the user around https://github.com/zaquestion/lab/blob/master/main.go#L69 so it's written in when the config is created. I'm not sure why I didn't implement it that way in the first place, so it may be some doing to make that happen.

Indeed, it would the possible situation of `core.user` being empty. I'm going to open a new issue, since this one will be solved by @prarit 's revert, and will prepare a patch with this change and propose other to see if you guys agree.

Thank you both :)
