### ISSUE TITLE
fork cmd fails to clone projects from subgroups

### ISSUE THREAD

**Issue by bmeneguele** [zaquestion/lab#424]
Projects placed within multiple levels of subgroups cause the `lab fork` to actually fork the project in gitlab, but don't clone it to the local machine:
```
$ lab fork namespace/subgroup1/project
fatal: repository 'subgroup1' does not exist
2020/09/09 12:21:52 clone.go:28: exit status 128
```
From my point of view the code handling the clone from `fork` only considers the first project's path level instead of the "last", since that's how gitlab works: in a fork situation it basically copies the project name the user is forking to user's namespace.

**Comment by prarit** [comment]
This can be closed based on the above merge.
