### ISSUE TITLE
Add support for gitlab snippets

### ISSUE THREAD

**Issue by Johnny-Malizia** [zaquestion/lab#43]
Sending large amounts of text to a gist was a long time favorite of mine to quickly share/document information with the rest of my team. 

Having the equivalent for gitlab would be extremely handy.

Mimicking the API here would be ideal https://github.com/defunkt/gist

**Comment by zaquestion** [comment]
Work has started on this current progress on https://github.com/zaquestion/lab/tree/snippets
Still needs tests, but should have something out over the weekend.

**Comment by zaquestion** [comment]
There are some limitations in the https://github.com/xanzy/go-gitlab API
- Cannot create snippets with a "description"
- Only supports project level snippet

Planning to PR their API to add support for those. They've already brought in: https://github.com/xanzy/go-gitlab/pull/247 to assist with returning the web_url

**Comment by zaquestion** [comment]
Support for personal snippets: https://github.com/xanzy/go-gitlab/pull/252 & https://github.com/xanzy/go-gitlab/pull/254

**Comment by zaquestion** [comment]
@Johnny-Malizia Support added in 0.6.0 for creating, listing, and deleting snippets enjoy!
