### ISSUE TITLE
Add diff to commit comments in 'mr show' output

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#439]
I was hoping to display diffs, or a least the commit ID in a note made on a commit.  However, it seems like I can't get that information or at least go-gitlab doesn't provide it.

See 

https://gitlab.com/bichon-project/bichon/-/issues/30

for details.

You can see this problem reproduced in lab with

```
diff --git a/cmd/issue_show.go b/cmd/issue_show.go
index 94762df148ab..b8356d34bfb2 100644
--- a/cmd/issue_show.go
+++ b/cmd/issue_show.go
@@ -169,6 +169,9 @@ func PrintDiscussions(discussions []*gitlab.Discussion, since string, idstr stri
                        printit(`
 %s-----------------------------------`, indentHeader)
 
+                       if note.Position != nil && i == 0 {
+                               fmt.Println("\n", indentHeader, note.Position)
+                       }
                        if time.Time(*note.UpdatedAt).After(CompareTime) {
                                printit = color.New(color.Bold).PrintfFunc()
                        }

```

**Comment by zaquestion** [comment]
Tried this locally and I was able to see the position information. Of note, you'll only see position info on notes in discussions that are actually diff comments. In trying to fiddle with the output, I'm not sure how to actually get the diff chunk from what's returned tho. Hopefully your git-fu is better than mine, it seems like we'll have to do something like
```
git diff -U10 <base sha> <head sha> -- <file>
# git diff -U10 note.Position.BaseSHA note.Position.HeadSHA -- note.Position.NewPath
```
`-U10` to get enough diff context

and then parse through the headers to find the appropriate offset to show.

**Comment by prarit** [comment]
OOOOOOOOOOOOOOOOOHHHHHHHHHHHHHHHHHHH :)

It's a *cumulative* diff, not the commit itself that gets commented on!
