### ISSUE TITLE
lab errors when run outside a git repo for commands where that's okay

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#446]
Provided the command isn't part of the skipinit logic, lab will error when run outside of a git repo. It's a pretty small set of commands that make any kind of sense outside of git repo to begin with so it's a low impact bug.

```
$ lab project create tests/labproject
fatal: --local can only be used inside a git repository
2020/09/30 22:30:30 root.go:289: No default remote found
// rest of output ...
```

As far as impacted commands, at least some of the `snippet` and `project` operations are affected, I could be forgetting some other command trees that would be affected tho.

We should probably guard this case by checking if we're actually in a git repo

**Comment by bmeneguele** [comment]
Hmm.. interesting.. I'm going to take a look on that.

**Comment by bmeneguele** [comment]
From my pov, ideally, the whole "remote discovery" code should happen only for commands running from within a valid repo dir, not only the "--local" error caused by the `git.go:GetLocalRemotesFromFile()`, since this error is masked by the go-gitlab lib for the other commands.

**Comment by zaquestion** [comment]
Good call, thanks for getting a fix it super quick ❤️

**Comment by prarit** [comment]
This can be closed based on the above merge.
