### ISSUE TITLE
Documented completion for powershell not being generated

### ISSUE THREAD

**Issue by DubKF** [zaquestion/lab#447]
According to the [readme line 118](https://github.com/zaquestion/lab/blob/master/README.md#L118)
lab should generate auto completion not only for bash / zsh, but also for **elvish, fish, powershell**  

However, in the current version the powershell completion doesn't work any longer and it seems other shells apart from bash / zsh might also be affected.

```
 15:17:22 $ lab version
git version 2.22.0.windows.1
lab version 0.17.2
 15:17:31 $ lab completion powershell
only 'bash' or 'zsh' allowed

```

Was the support simply dropped (potential documentation update needed) or should it still be working in version 0.17.2?

**Comment by zaquestion** [comment]
Hi @DubKF, those shell completions exist, however they haven't been released yet. Apologies the readme itself can sometimes get out of sync with the latest release. The docs (https://zaquestion.github.io/lab/) and and cmd help text will always be accurate to the latest release fwiw. 

Lot's of great stuff coming in `0.18`, we're actively adding more too it and hoping to get the release out soon. It's somewhat tied up in https://github.com/zaquestion/lab/issues/406
