### ISSUE TITLE
token asked for wrong domain

### ISSUE THREAD

**Issue by glensc** [zaquestion/lab#45]
```
$ lab remote -v
Enter default GitLab host (default: https://gitlab.com): https://gitlab.example.net 
Enter default GitLab user: glen
Enter default GitLab token (scope: api ):
Create here: https://gitlab.com/profile/personal_access_tokens[]
```

should say: https://gitlab.example.net/profile/personal_access_tokens

also, there's some usability issue, the cursor is placed in `[]`, i.e without newline. perhaps print that information before prompting user (swap two last lines)

also, the `stty echo` needs to be trurned off, not to show token when pasting it to terminal.

**Comment by zaquestion** [comment]
Thanks for reporting!

**Comment by zaquestion** [comment]
@glensc I've put in a fix, will keep this open for a bit longer to give you a chance to try it out first.
