### ISSUE TITLE
git: command failure when using <pushurl>

### ISSUE THREAD

**Issue by bmeneguele** [zaquestion/lab#456]
Git allows the user to add a `<pushurl>` option to git-config to be used as the push-only URL, instead of the usual `<url>`, which is then left as the fetch-only URL. `lab` doesn't consider the user may be using `<pushurl>` and because of that commands like `lab mr create` fails to run while trying to find the branch in the project pointed by the "fetch" URL, in other words, `<url>`:
```
$ lab mr create origin <branch>
2020/09/30 18:59:21 mr_create.go:104: aborting MR, source branch 3-Makefile-GIT-macro not present on remote origin. did you forget to push?: GET https://gitlab.com/api/v4/projects/13604247/repository/commits/3-Makefile-GIT-macro: 404 {message: 404 Commit Not Found}
```
And from git-push manpage:
```
[remote "<name>"]
    url = <url>
    pushurl = <pushurl>
    push = <refspec>
    fetch = <refspec>

The <pushurl> is used for pushes only. It is optional and defaults to <url>.
```
With that, we also should consider this precedence in case the user uses `<pushurl>`.

**Comment by prarit** [comment]
This can be closed based on the above merge.
