### ISSUE TITLE
Suggestion: README Edit

### ISSUE THREAD

**Issue by fosterlynch** [zaquestion/lab#465]
I had an API token expire and whenever calling ```lab``` all I got was an error saying token is expired: there was no way to use any of the help commands.

After looking through the config documentation listed in this repo, it didn't seem like I had any environment variables set or any ```~/.config/lab...``` directories, as listed. However I did have a ```lab.hcl``` file which after manually changing the token inside that file, that did the trick. 

Suggestion may be to edit the README to include that lab.hcl file for config management?

**Comment by bmeneguele** [comment]
Hi @fosterlynch ,

are you using which version of the lab tool? The version 0.17.2 indeed has this issue of API token being required even to issue "lab --help|--version", however it was already fixed alongside many other fixes and changes regarding config management in the current master branch (that's also the reason you don't see anything about the .hcl file in the README file anymore). All these fixes/changes will be available when 0.18.0 is launched.

**Comment by fosterlynch** [comment]
Ah yes, just looked and I am indeed on 0.17.2.  Thank you for the clarification!

**Comment by zaquestion** [comment]
Yeah confusing is probably from the readme showing information for the next release of lab instead of the latest `0.17.2` release. Usually we wouldn't go this long between releases
