### ISSUE TITLE
Update the configured token

### ISSUE THREAD

**Issue by mircohaug** [zaquestion/lab#472]
For the initial configuration by typing `lab` in a shell, I used a token with insufficient permissions. I want to update this token but I do not know how to do this. I did not find a configuration file at any of the paths mentioned in the docs. I did find an entry in the systems key ring but changing or deleting the saved value had no effect. Reinstalling via brew also did not reset the configuration.

So how do I initialize lab with a new configuration or update the existing one?

I am on mac and installed lab via brew.

**Comment by prarit** [comment]
Thanks for the report @mircohaug .  Can I ask what paths you looked at for the config files?  I can give you instructions on how to update, however, I'm more concerned that the documentation may be lacking.

**Comment by zaquestion** [comment]
This is likely a drift between the current readme and latest `0.17.2` release which still points to `~/.config/lab.hcl` instead of `~/.config/lab.toml`

**Comment by prarit** [comment]
@mircohaug, if you're using 0.17.2 then it's likely that as @zaquestion says you're looking at ~/.config/lab.hcl.  You can look in ~/.config/lab/lab.toml for the token.

**Comment by mircohaug** [comment]
@zaquestion was right the config file `lab.hcl` exists and contains the values.
```
$ lab version
git version 2.28.0
lab version 0.17.2
```
I was looking at `~/.config/lab/lab.toml` the env var `LAB_CORE_TOKEN` and locally in `.git/lab/lab.toml`
