### ISSUE TITLE
3+ hour travis-ci.org delays:  Solution is to migrate to travis-ci.com

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#474]
@zaquestion , 

There are now long delays on travis-ci.org.  I migrated in about 2-3 mins last night.  Not sure if you have done the same but the tests on lab are still being run against travis-ci.org.  Is there any chance you could migrate lab?

https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

P.

**Comment by zaquestion** [comment]
I think it should be migrated now. Longer term will all be gitlab obviously #406

**Comment by prarit** [comment]
Thanks.  As an additional annoyance I now realize I've added an extra mouse click in order to get build results. :(
