### ISSUE TITLE
build failed by `undefined: gitlab.ListDescendantGroupsOptions` on branch projectgroups

### ISSUE THREAD

**Issue by huhuang03** [zaquestion/lab#490]
I want use your create group feature https://github.com/zaquestion/lab/pull/450.

But when I run `go build` on branch `projectgroups`. The error throws:

```
xx@xxs-MacBook-Pro lab % go get
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading google.golang.org/appengine v1.6.6
go: downloading github.com/golang/protobuf v1.4.2
go: downloading google.golang.org/protobuf v1.25.0
# github.com/zaquestion/lab/internal/gitlab
internal/gitlab/gitlab.go:769:27: lab.Groups.ListDescendantGroups undefined (type *gitlab.GroupsService has no field or method ListDescendantGroups)
internal/gitlab/gitlab.go:769:62: undefined: gitlab.ListDescendantGroupsOptions
```

I can't figure out how to resolve this..

**Comment by bmeneguele** [comment]
Hi @huhuang03,

This branch/merge request is outdated wrt go-gitlab version that contains the `Groups.ListDescendantGroups` support.
Try to change the following line:

https://github.com/zaquestion/lab/blob/62523a3a712276b9a532e2ce92418a3dc6a7c476/go.mod#L25

to point to version `0.38.2` instead.

**Comment by bmeneguele** [comment]
This issue should be solved by the current state of the pull request.
