### ISSUE TITLE
Create additional gitlab lab test project for 'issue move'

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#498]
@zaquestion , I've added an 'issue move' command that allows users to move issues from one project to another.  I did not add tests as I need another project to target.  Is there any chance you could create a second test project that I could use?

Thanks :)

**Comment by prarit** [comment]
https://github.com/zaquestion/lab/pull/497

**Comment by prarit** [comment]
I wonder if you could open up permissions on https://gitlab.com/lab-testing/test ?

**Comment by bmeneguele** [comment]
@prarit , I've created the project https://gitlab.com/lab-testing/test_1 , does that is enough for testing or does it need some other change (e.g. repo specific config)?

**Comment by prarit** [comment]
I think that's fine but you'll have to filter out emails for that project.  Everytime someone does a build you'll get email.  You might want to give it a more descriptive project name like "FILTER_THIS_OUT_TEST_1" or something.  Go on, ask me how I know :)

**Comment by bmeneguele** [comment]
But the project is under lab-testing and only those really "following" the project will receive the email notification, isn't it?

**Comment by zaquestion** [comment]
@prarit @bmeneguele Need any thing from me on this? Looks Like Bruno might have got it sorted?

Sorry for the late reply I'm a bit underwater with lab stuff... If you're blocked on me in the future don't hesitate to email me directly at zaquestion@gmail.com 

I'll work on getting the `0.18.0` release out next week as well.

**Comment by bmeneguele** [comment]
Yep, it's now solved and working as expected :).
I forgot to close the issue.
