### ISSUE TITLE
Couldn't create merge request, Cannot read property 'green' of undefined

### ISSUE THREAD

**Issue by koshyviv** [zaquestion/lab#530]
I'm getting this issue whenever i try to create a MR, I'm really not sure what is going on and couldn't find anything similar posted previously. Can someone please help

```
vivek@ideacrest-0020:~/offset-widgets$ lab mr -b dev -t staging -m "Test MR" -a vivek.ideacrest -v
Verbose option used. Detailed logging information will be emitted.



Getting base branch information

Getting base branch name : 
Argument provided : dev
Base branch name obtained : dev

Getting remote of branch : dev
Executing git config branch.dev.remote
Remote obtained : origin


Getting URL of remote : origin
Executing  git config remote.origin.url
URL of remote obtained : git@gitlab.com:greenstory/offset-widgets.git


gitlab host obtained : gitlab.com

Project name derived from host : greenstory/offset-widgets

Getting gitlab project info for : greenstory/offset-widgets
Couldn't create merge request
Cannot read property 'green' of undefined
```

**Comment by fmuellner** [comment]
It sounds like you picked the "wrong" lab. Neither the command line options nor the error messages match the code in this project.

Maybe the `--help` or `--version` flags provide some information to identify the correct project?

**Comment by zaquestion** [comment]
@profclems is this one of yours?

**Comment by profclems** [comment]
> @profclems is this one of yours?

I don't think so. None of the error messages and logs matches any part of our code.

**Comment by koshyviv** [comment]
This was an issue with the wrong reference of `lab`. Sorry for the delay.
