### ISSUE TITLE
windows build error blocking 0.18.0 release

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#554]
https://www.travis-ci.com/github/zaquestion/lab/builds/212062231
```
  ⨯ release failed after 257.68s error=failed to build for windows_386: go: downloading github.com/inconshreveable/mousetrap v1.0.0

go: downloading github.com/Microsoft/go-winio v0.4.15

# github.com/zaquestion/lab/cmd

cmd/util.go:333:25: cannot use syscall.Stdout (type syscall.Handle) as type int in argument to terminal.IsTerminal

cmd/util.go:333:65: cannot use syscall.Stderr (type syscall.Handle) as type int in argument to terminal.IsTerminal
```

After we fix this, just need to recreate the `v0.18.0` release and travis should roll it out. cc @bmeneguele @prarit

**Comment by bmeneguele** [comment]
Oh! That's on me. Didn't know the syscall lib would change the return type there for Windows.
I'm going to solve it ASAP.

**Comment by bmeneguele** [comment]
@zaquestion just merged the fix.
Feel free to go ahead and recreate the release.
