### ISSUE TITLE
lab 0.18.0 behavior change

### ISSUE THREAD

**Issue by chenrui333** [zaquestion/lab#558]
👋  looks like the lab 0.18.0 behavior got changed (it requires the gitlab PAT before proceeding to do something meaningful) and now the test started not working.

```
    ENV["LAB_CORE_USER"] = "test_user"
    ENV["LAB_CORE_HOST"] = "https://gitlab.com"
    ENV["LAB_CORE_TOKEN"] = "dummy"
    ENV["GIT_AUTHOR_NAME"] = "test user"
    ENV["GIT_AUTHOR_EMAIL"] = "test@example.com"
    ENV["GIT_COMMITTER_NAME"] = "test user"
    ENV["GIT_COMMITTER_EMAIL"] = "test@example.com"
    system "git", "init"
    %w[haunted house].each { |f| touch testpath/f }
    system "git", "add", "haunted", "house"
    system "git", "commit", "-a", "-m", "Initial Commit"
    assert_equal "haunted\nhouse", shell_output("#{bin}/lab ls-files").strip
```

Interesting enough, I found the similar [test code](https://github.com/zaquestion/lab/blob/0ff2ff02b4ecffbbeb1f695556486d104d30f56e/.goreleaser.yml#L20-L25) in the codebase. Not sure if some real test token was used in the goreleaser process.

relates to https://github.com/Homebrew/homebrew-core/pull/68377

**Comment by bmeneguele** [comment]
Hi @chenrui333 , thanks for opening this issue.
I'll take a look on it and also make sure we have a test for catching it earlier.
Sorry for the incovinience.

**Comment by chenrui333** [comment]
no worries, thanks for picking this up.

**Comment by chenrui333** [comment]
Any updates?

**Comment by bmeneguele** [comment]
> 
> 
> Any updates?

Not yet, sorry.
Didn't have time to look at it :( but I'll give my word I'll take care of it early next week (Monday).

**Comment by prarit** [comment]
@bmeneguele @chenrui333 :  I think I have a solution.  Will update in a minute.

**Comment by bmeneguele** [comment]
@prarit thanks for the help :) didn't have time to get a closer look at it.
One thing I noticed is that `lab -h` and `lab --help` have different behaviors too: the first requires API auth, while the last doesnt.
But I think it's something for another issue.

**Comment by prarit** [comment]
> @prarit thanks for the help :) didn't have time to get a closer look at it.
> One thing I noticed is that `lab -h` and `lab --help` have different behaviors too: the first requires API auth, while the last doesnt.
> But I think it's something for another issue.

I think it has something to do with the way we're wrapping 'git'.  'lab -h' outputs the git help, while 'lab --help' outputs lab's help.

**Comment by chenrui333** [comment]
much better than last time
```
==> /usr/local/Cellar/lab/0.18.0/bin/lab ls-files
2021/01/11 15:34:30 root.go:146: No default remote found
Error: lab: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <"haunted\n" + "house"> expected but was
<"Config saved to /private/tmp/lab-test-20210111-16852-15321lo/.config/lab/lab.toml\n" +
"haunted\n" +
"house">.

diff:
+ Config saved to /private/tmp/lab-test-20210111-16852-15321lo/.config/lab/lab.toml
  haunted
  house

folded diff:
+ Config saved to /private/tmp/lab-test-20210111-16852-15321lo/.config/lab/lab.t
+ oml
  haunted
  house
```

**Comment by prarit** [comment]
Thanks @chenrui333, I've added one additonal change.  Can you do another test on #559 ?

**Comment by bmeneguele** [comment]
> > @prarit thanks for the help :) didn't have time to get a closer look at it.
> > One thing I noticed is that `lab -h` and `lab --help` have different behaviors too: the first requires API auth, while the last doesnt.
> > But I think it's something for another issue.
> 
> I think it has something to do with the way we're wrapping 'git'. 'lab -h' outputs the git help, while 'lab --help' outputs lab's help.

Yes, it is. Last time I changed the code I didn't notice the diff. I'm going to review it.

**Comment by chenrui333** [comment]
Close as it is resolved. Thanks @prarit @bmeneguele!
