### ISSUE TITLE
using 'lab mr edit' to update the commit message for the MR does not generate any email

### ISSUE THREAD

**Issue by darcari** [zaquestion/lab#571]
I can see that the MR was in fact update, but no one was notified.

**Comment by fmuellner** [comment]
That's a gitlab issue, not lab.

At least with the gitlab versions I've been working with, there's no notification when updating a MR subject, neither via the API nor the web UI.

**Comment by darcari** [comment]
OK - Thanks.

**Comment by prarit** [comment]
Sorry @darcari  I meant file a ticket on the kernel repo so we can track it.
