### ISSUE TITLE
lab: mr_approve test failures

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#573]
Need to look at these failures: https://travis-ci.com/github/zaquestion/lab/builds/213947699

@bmeneguele any ideas?  I'll take a closer look too.

**Comment by bmeneguele** [comment]
@prarit Thanks for looking into it.
The major issue I see with the tests is when a new MR or an issue is added changing the expected string required by another test.

One option I thought about was to make the changes in CI time, letting the test code pointing to a generic string, i.e. "{LATEST_MERGEREQUEST}", "{FIRST_ISSUE}", ..., and during CI it's `sed`'ed to the real value got from an API query done by a standalone test script.
One disadvantage with this approach is that we add another step for testing in a local environment, but it can be solved by adding it to the `test` makefile target.

Do you and @zaquestion think it's something interesting + worthy of looking at?

**Comment by prarit** [comment]
I've solved this with 8c6eec143447 ("mr approve: Fix unapprove test failures")
