### ISSUE TITLE
[Discussion] Code sharing between glab and lab?

### ISSUE THREAD

**Issue by profclems** [zaquestion/lab#577]
I am the maintainer of [`glab`](https://github.com/profclems/glab), an opinionated open source GitLab CLI tool.

Though the tool is heavily inspired by [`gh`](https://github.com/cli/cli), we can't deny the fact that some `glab` commands were adopted from `lab`.
Most especially, commands related to `ci` such as `ci view` and `ci trace` were heavily inspired by `lab`, which I initially failed to properly credit `lab` for. Our readme now mentions lab https://github.com/profclems/glab#what-about-lab.

I created `glab` because I personally want to use a separate tool that's more opinionated and not wrap git for me. `Lab` is a great tool and works more like `Hub`.

I opened this issue to suggest a direct codesharing between `lab` and `glab` for commands related to `ci` so both tools can benefit from a wider set of maintainers.

Aside from that, I'm open to other discussions that will help in driving the future of both tools.

**Comment by zaquestion** [comment]
This is welcome to remain open, I haven't had a chance to respond but we'll be in touch either way :D
