### ISSUE TITLE
Cannot filter MRs using some labels

### ISSUE THREAD

**Issue by jbenc** [zaquestion/lab#580]
```
$ lab mr list -l 'Subsystem:net'
2021/02/08 16:21:53 mr_list.go:50: Label 'Subsystem:net' is ambiguous
Error: User authentication failed.  This is likely due to a misconfigured Personal Access Token.  Verify the token or token_load config settings before attempting to authenticate.
```

The error message is misleading (which would be worth fixing, too), it's not a problem with my token. Other queries work fine.

The problem is that in the same project, there is also a Subsystem:netdrv label. It seems that -l matches on any prefix of the label. This makes it impossible to filter on Subsystem:net.

**Comment by prarit** [comment]
This should be fixable.  We've probably just been lazy about exact matches ;)

**Comment by bmeneguele** [comment]
Hey @jbenc,

I've created a PR for fixing both points you mentioned:
1. the config error message
2. label matching code

With the new code, you should be **informed** about the ambiguity of that specific label, but not receive an error. And the exact match prevails.

**Comment by prarit** [comment]
@bmeneguele see my comment in the MR.  It's possible that I'm doing it wrong but I can't seem to get -x to work.

**Comment by bmeneguele** [comment]
Just replied there. You used `-x` (exact match for searching terms) instead of `-l`.
