### ISSUE TITLE
approve and unapprove message failures can be better

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#582]
When I attempt to approve or unapprove on a Project that I don't have approve permissions for, I get the following error:

2021/02/10 10:58:17 mr_approve.go:56: POST https://gitlab.com/api/v4/projects/XXXX/merge_requests/208/approve: 403 {message: 403 Forbidden}

It would be good to provide some better error messaging.

And, yes, I already have a patch :)

**Comment by bmeneguele** [comment]
Closing issue based on the PR already merged.
