### ISSUE TITLE
Windows syscalls error

### ISSUE THREAD

**Issue by bmeneguele** [zaquestion/lab#598]
While preparing a new release for `lab` the build system found the following error:
```
cmd\util.go:448:20: undefined: syscall.Dup
cmd\util.go:449:6: undefined: syscall.Dup2
cmd\util.go:459:7: undefined: syscall.Dup2
cmd\util.go:460:26: cannot use pager.stdout (type int) as type syscall.Handle in argument to syscall.Close
make: *** [Makefile:5: build] Error 2
```

These are Linux vs Windows syscall issues. While the stdout case is simple to solve, the Dup and Dup2() require some kernel32.dll calls. I'm going to create a layer of compatibility for these calls, so we can populate it for future needs.

**Comment by fmuellner** [comment]
Oh no, I'm sorry for that :-(

**Comment by bmeneguele** [comment]
No worries at all @fmuellner .. we never really expect this kind of issue, even more, when we're totally focused on the general solution/feature. And that's not the first time we've stumbled on that.. nor the last. ;-)

**Comment by bmeneguele** [comment]
@fmuellner btw, take a look at the MR and give your review there.
