### ISSUE TITLE
Command `lab mr` returns error

### ISSUE THREAD

**Issue by adamryman** [zaquestion/lab#6]
After running `lab mr` and writing a message and exiting the editor I get the error:

```
2017/09/06 17:42:14 POST https:/URL_RETRACTED/api/v4/projects/PROJECT_ID_RETRACTED/merge_requests: 403 {message: 403 Forbidden}
```

Not sure what went wrong.

Possibly need to add more debug logging.

**Comment by zaquestion** [comment]
@adamryman I haven't been able to reproduce this, are you still experiencing the issue?

**Comment by adamryman** [comment]
On my latest computer I am not having this issue. I do not wish to try and reproduce if it is not effecting anyone else.

¯\_(ツ)_/¯
