### ISSUE TITLE
No chance to edit cover letter: lab mr create origin --cover-letter  -m "...blah blah..."

### ISSUE THREAD

**Issue by LennySzubowicz** [zaquestion/lab#609]
I wasn't given any chance to edit the cover letter. My merge request was immediately posted and it had no cover letter. So it was malformed.

[lszubowi@lszubowi rhel-8]$ lab mr create origin --cover-letter  -m "...blah blah..."

[lszubowi@lszubowi rhel-8]$ git config core.editor
vim
[lszubowi@lszubowi rhel-8]$ echo $GIT_EDITOR
vim

[lszubowi@lszubowi rhel-8]$ lab --version
git version 2.27.0
lab version 0.20.0

Is -m is incompatible with --cover-letter  ?  If so, lab should fail my request.

**Comment by prarit** [comment]
Hey @LennySzubowicz , the issue here is the use of the -m option.  -m assumes you've completed the title and description for the MR.  If you want to edit the MR before submitting you should just use

`lab mr create origin --cover-letter`

which will open $GIT_EDITOR.

**Comment by LennySzubowicz** [comment]
@prarit what if I had thrown in -F that is, which would win?

  -c, --cover-letter           do not comment changelog and diffstat
  -F, --file string            use the given file as the Description
  -m, --message stringArray    use the given <msg>; multiple -m are concatenated as separate paragraphs

Note that lab mr create --help doesn't even mention $GIT_EDITOR and the help text is pretty sparse.

Perhaps there should be an explicit --edit similar to what git has for commits.

Lastly, is the git config core.editor setting enough? That doesn't explicitly create the GIT_EDITOR environment variable. So I'm guessing that lab only looks for the environment variable.

**Comment by prarit** [comment]
> @prarit what if I had thrown in -F that is, which would win?
> 
> -c, --cover-letter do not comment changelog and diffstat
> -F, --file string use the given file as the Description
> -m, --message stringArray use the given ; multiple -m are concatenated as separate paragraphs
> 
> Note that lab mr create --help doesn't even mention $GIT_EDITOR and the help text is pretty sparse.

It's not something that is specific to lab mr create.  lab issue create, lab mr edit, etc,. .all use $GIT_EDITOR.  Something should be added to the README.md about this IMO.

> 
> Perhaps there should be an explicit --edit similar to what git has for commits.
> 

That's not a bad idea.  I'll look into it.

> Lastly, is the git config core.editor setting enough? That doesn't explicitly create the GIT_EDITOR environment variable. So I'm guessing that lab only looks for the environment variable.

We only are looking at $GIT_EDITOR.  You do raise a good point.  I'll think about adding 'git config core.editor'.  I'll look at what git does and mimic that choice of options.

**Comment by prarit** [comment]
And 'blah blah blah ..." is not a good descriptive commit message @LennySzubowicz  :) :)

**Comment by bmeneguele** [comment]
> Is -m is incompatible with --cover-letter ? If so, lab should fail my request.

I agree: `-m`, `-F` and `-c` follow a strict presence order when used together. The user should 1) be warned about in runtime, 2) have it noted in the `--help` or 3) not be allowed to run these options together, following the same behavior as `git`.

IMO 2) and 3) should be adopted.

**Comment by bmeneguele** [comment]
oh, it should not have been closed. The merge **partially** solves the issue.

**Comment by prarit** [comment]
I have implemented the core.editor check in #642
