### ISSUE TITLE
My pending MR is visible in webui, but doesn't show in lab mr list 

### ISSUE THREAD

**Issue by LennySzubowicz** [zaquestion/lab#614]
In particular:
https://gitlab.com/redhat/rhel/src/kernel/rhel-8/-/merge_requests/99

This is a MR for 8.4 and it appears that lab mr list defaults to showing pending merges for main.
My current branch in my local git clone appears to not matter

However, I can it see it by:

lab mr list origin 8.4

It's not obvious from the help that the lab mr list is branch sensitive.

**Comment by prarit** [comment]
There is a --all that obtains *all* MRs, and that's what it's for.  I'll update the help for 'lab mr list' to make it more obvious.

**Comment by prarit** [comment]
Okay, so I think you're confused and you ended up with a result you did not expect.

```
'lab mr list' # will show the last 20 updated MRs.
'lab mr list --all' # will show all MRs.
'lab mr list origin 8.4' # will show all MRs matching string '8.4'
```

Looking at the help text, I don't see a need for a change.  I agree there's a lot of options there but I think we're okay on the documentation front.

**Comment by prarit** [comment]
Oh, to be clear the string match is against the MR title and description.

**Comment by LennySzubowicz** [comment]
Yes, I see now that the "8.4" is a string match on title. I was wrong in thinking it was the branch target.

Not really obvious from lab mr list --help that default is 20.

 -n says it's 10.


Flags:
  -l, --label strings          filter merge requests by label
  -s, --state string           filter merge requests by state (all/opened/closed/merged) (default "opened")
  -n, --number int             number of merge requests to return (default 10)
  -t, --target-branch string   filter merge requests by target branch
      --milestone string       list only MRs for the given milestone
  -a, --all                    list all MRs on the project
  -m, --mine                   list only MRs assigned to me
      --assignee string        list only MRs assigned to $username
      --order string           display order (updated_at/created_at) (default "updated_at")
      --sort string            sort order (desc/asc) (default "desc")
      --draft                  list MRs marked as draft
      --ready                  list MRs not marked as draft
      --no-conflicts           list only MRs that can be merged
      --conflicts              list only MRs that cannot be merged
  -x, --exact-match            match on the exact (case-insensitive) search terms
  -h, --help                   help for list

**Comment by prarit** [comment]
I think these issues are solved.
