### ISSUE TITLE
Default color for changelog text from lab mr show <mr id> is not legible on white background

### ISSUE THREAD

**Issue by LennySzubowicz** [zaquestion/lab#616]
The default color for the merge change log text appears to be light grey, which is barely legible on a white terminal background.

Is there a config setting for .config/lab/lab.toml to change this?

**Comment by prarit** [comment]
There isn't.  It's because I'm lazy and assumed everyone would use a black/dark background :)  This is, FWIW, a dup of https://github.com/zaquestion/lab/issues/596
