### ISSUE TITLE
What does it mean for an MR to be "assigned" to someone?

### ISSUE THREAD

**Issue by LennySzubowicz** [zaquestion/lab#617]
At first glance I expected "lab mr list --mine" to show the pending MRs that I have submitted.

But the help text does say that --mine will show the MRs that are "assigned" to me. Does that mean MRs for which I'm a required reviewer?

If that's the case, it would be useful to have some listing option to show me the pending MRs that I (or a specified user) have submitted.

**Comment by bmeneguele** [comment]
I have to agree with you, the `--mine` is indeed misleading: it really gives the feeling of "I own this MR" or "I'm the author of that".
I'm going to submit a MR for getting rid of it and adding the `--author` option. Lets see what others think about it.
