### ISSUE TITLE
GitLab filtering by issue labels

### ISSUE THREAD

**Issue by nkprince007** [zaquestion/lab#62]
```bash
$ lab issue list by-labels "bug, help wanted"
```

should list the issues based on labels. An addition to MRs by labels and assignees would be a better addition too.

**Comment by nkprince007** [comment]
I've been working with GitHub & GitLab APIs recently. I'd like to further this project by effectively implementing the APIs. Checkout our project [here on GitLab](https://gitlab.com/gitmate/open-source/IGitt).

**Comment by zaquestion** [comment]
I love the idea of being able to filter by labels. What do you think of using flags to pass the values in instead. 
```
Flags:
  -h, --help               help for issue
  -l, --label stringSlice  filter issues by label
  -a, --assignee string    filter issues by assignee
```

Feel free to submit a PR and if you're so inclined the functionality would probably sit well on `mr list` as well. Otherwise I'll probably get around to this before the new year.

**Comment by nkprince007** [comment]
Hey, I'm done with labels implementation, but the tests require help. Can you add some labels to issues and give me the test data? @zaquestion

**Comment by nkprince007** [comment]
Uhm, also @zaquestion, the go-gitlab, doesn't really offer a search by `assigneeName` we'd need to use the `AssigneeID`, so the filtering is a bit difficult.

**Comment by zaquestion** [comment]
Thanks @nkprince007 Added some more issues and mrs with labels and assignees on them. Tried to provide some options to work with.
https://gitlab.com/zaquestion/test/merge_requests
https://gitlab.com/zaquestion/test/issues

**Comment by nkprince007** [comment]
Also, I've updated the PR to filter by state. I'll add tests to them too :) thanks for the help :)

**Comment by zaquestion** [comment]
Added some more mrs and issues to cover all the states if you need.

**Comment by nkprince007** [comment]
@zaquestion is there some way to run tests locally?

**Comment by zaquestion** [comment]
`make test` will do the trick, many of the tests (as you may have notices) exec the lab binary. They'll require an internet connection, but otherwise you should be good.

**Comment by nkprince007** [comment]
Ok, thanks @zaquestion

**Comment by nkprince007** [comment]
I've updated the PR, tests pass now. Review again, please.
