### ISSUE TITLE
Help for "lab mr show --no-color-diff"  looks wrong

### ISSUE THREAD

**Issue by LennySzubowicz** [zaquestion/lab#625]
A nit.

--no-color-diff   show color diffs in comments

Shouldn't this be: Don't show color diffs in comments?

And when would comments be colorized? If someone proposes a code revision in a comment?

**Comment by prarit** [comment]
haha -- good catch.  That's an easy fix.

**Comment by prarit** [comment]
Yes, code revision comments are colorized.  You can see this in the GitLab WebUI, and lab mimics that output.  Albeit on a dark backround ;)
