### ISSUE TITLE
Addition of verbose flag

### ISSUE THREAD

**Issue by nkprince007** [zaquestion/lab#63]
```bash
$ lab issue ls --verbose
#1 Issue title
        Issue link
        Issue description
        Assignees, Labels
#2 Issue title
        Issue link
        Issue description
        Assignees, Labels
...
```
Would love to have such an interface.

**Comment by zaquestion** [comment]
Along the same lines, `lab issue show/get` is something I've thought about that showed more detailed view. Theres a GitLab issue open for creating a lab cli that suggests and interesting design here: https://gitlab.com/gitlab-org/gitlab-ce/issues/17575#note_11927381

**Comment by nkprince007** [comment]
Can we have a discussion over gitter?

**Comment by nkprince007** [comment]
How does this look @zaquestion? https://asciinema.org/a/xIsmfvlSB8I7BIRjARYJooOxo
