### ISSUE TITLE
"lab mr show" output with PAGER=most is unreadable, readable but mangled with PAGER=less

### ISSUE THREAD

**Issue by dvlasenk** [zaquestion/lab#632]
```
With PAGER=most:

!4 af_unix: fix struct pid memory leak
===================================

^[[38;5;252m^[[38;5;252m  ^[[38;5;252mFrom: Eric Dumazet ^[[38;5;35;1medumazet@google.com^[[38;5;252m ^[[38;5;30;4mmailto:edumazet@google.com^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[3$
  ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m $
^[[38;5;252m^[[38;5;252m  ^[[38;5;252mBugzilla: ^[[38;5;30;4mhttps://bugzilla.redhat.com/show_bug.cgi?id=1901744^[[38;5;252m ^[[38;5;252mUpstream^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m $
^[[38;5;252m  ^[[38;5;252mStatus:^[[38;5;252m linux.git ^[[38;5;252mBuild Info:^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^$
^[[38;5;30;4m^[[38;5;30;4m  ^[[38;5;30;4mhttps://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33290816^[[38;5;252m ^[[38;5;252mTested:
^[[38;5;252m  ^[[38;5;252mreproducer in^[[38;5;252m bugzilla^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5$
  ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m $
^[[38;5;252m^[[38;5;252m  ^[[38;5;252mContext differences, due to upstream commit 7cc05662682d (net: remove^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m
^[[38;5;252m  ^[[38;5;252msock_^[[38;5;252miocb) not having been backported to^[[38;5;252m RHEL-7.^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;$
....rest snipped...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

With PAGER=less (or with PAGER unset, "less" is the default pager):

!4 af_unix: fix struct pid memory leak
===================================

  From: Eric Dumazet edumazet@google.com mailto:edumazet@google.com           
                                                                              
  Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901744 Upstream      
  Status: linux.git Build Info:                                               
  https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33290816 Tested:
  reproducer in bugzilla                                                      
                                                                              
  Context differences, due to upstream commit 7cc05662682d (net: remove       
  sock_iocb) not having been backported to RHEL-7.
...
^^^^^^^^^^^^^^

This looks marginally better (I actually can read it), but lines are
incorrectly wrapped, and the paging action does not actually happen -
after output, I end up in shell prompt, not in "less", so the intent
of letting me scroll over a large output is not achieved.

Only the forced "do not try to paginate" approach, like
"lab mr show N | cat" gives the right output - note that
lines are now CORRECTLY wrapped, for example "Upstream Status"
line does not attach itself to the tail of BZ url on previous
line):

!4 af_unix: fix struct pid memory leak
===================================
From: Eric Dumazet <edumazet@google.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901744
Upstream Status: linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33290816
Tested: reproducer in bugzilla

Context differences, due to upstream commit 7cc05662682d (net: remove sock_iocb) not having been backported to RHEL-7.
...
```

**Comment by bmeneguele** [comment]
@dvlasenk thanks for the report!

The issue here is that `lab` is using pagers for every output it produces that can go beyond a window size if the user doesn't pass the `--no-pager` option or when stdout/stderr it's not piped out to a pager, e.g., `lab mr show --comments | most`. With that, when using the `PAGER` env var `lab` won't avoid markdown rendering.

Both cases (line wrapping and colors) can be solved by using `--no-markdown|-M` option, which will not render the markdown in any case.  
If you don't really care about any markdown rendering, you can add the following lines to your config file:

```
[mr_show]
    no-markdown = true
```

With that, you don't need to pass `--no-markdown|-M` to any `lab mr show` calls.

**Comment by bmeneguele** [comment]
At the same time, I'm not sure why `most` isn't supporting the color codes there, it seems to have the usual support for that.

**Comment by dvlasenk** [comment]
Bruno, does it work for you?

**Comment by bmeneguele** [comment]
> Bruno, does it work for you?

I was able to reproduce the "issue" you reported, but using the `--no-markdown` (or `-M`) worked as expected, removing the glitches you saw. But I need to dig more to understand why `most`, specifically, isn't supporting the colors as it should.

**Comment by dvlasenk** [comment]
It does not work correctly with "less" as well: the lines are incorrectly wrapped (glued together). See my initial comment.

**Comment by dvlasenk** [comment]
> why most, specifically, isn't supporting the colors as it should.

It does not understand ^[[38;5;<8-bit color no>m escape sequence.
It likely understands only traditional 3-bit color escapes + 1 bit for "bright".
See https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by bmeneguele** [comment]
> It does not work correctly with "less" as well: the lines are incorrectly wrapped (glued together). See my initial comment.

Yes, but as I said, it's caused by the markdown rendering: when using `PAGER=less` `lab` will try to render the way it appears in WebUI, _which is also messed up with lines glued together_; while with `lab mr show | less` `lab` won't perform any markdown rendering, presenting the text the way it was first sent to gitlab.

The difference between `less` (with rendering) and WebUI results is due to the default line width wrapping applied by the engine.  
I'm going to check the engine documentation and see if this wrapping can be turned off and then verify the results.

**Comment by bmeneguele** [comment]
> > why most, specifically, isn't supporting the colors as it should.
> 
> It does not understand ^[[38;5;<8-bit color no>m escape sequence.
> It likely understands only traditional 3-bit color escapes + 1 bit for "bright".
> See https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

ahh ok! makes sense then.
