### ISSUE TITLE
Why `lab project list` show not my project

### ISSUE THREAD

**Issue by huhuang03** [zaquestion/lab#644]
I am on a windows.

And my config in C:/Users/myname/.conf/lab/lab.toml is:
```
[core]
  host = "https://gitlab.com"
  token = "my token I'm sure."
  user = "huhuang03"
```

But when I call `lab project list`, it shows some project none of them is mine.

```
PS E:\source> lab project list
leberwurscht/teardownwalls
technomancy/leiningen
jonan/heroes-of-wesnoth
jonan/k
hcs/hcs_utils
soeren/sspssptest
dpp/slothbeast
rocksoniko/easy
grup/grup
varac/test
rb/boner-project
jondo/pureimage
gropoutoux/bvcbvc
chiiph/leap_client
mcnair/mcnair-leap_client-fork
serates/dirk
vpujari/pdemo
verybigman/teams0
wktk/sandbox
alessioalex/pushover
```

How can I debug this?

**Comment by prarit** [comment]
'lab project list' only shows the open projects.  You want to execute 'lab project list --member' to show projects that you are a member of.

**Comment by huhuang03** [comment]
Thank you for your reply. `lab project list --member` can show project I'm member.
