### ISSUE TITLE
Add merge-request option for "Merge when pipeline succeeds"

### ISSUE THREAD

**Issue by galan** [zaquestion/lab#653]
It would be helpful if lab would provide an option to enable the ["Merge when pipeline succeeds"](https://docs.gitlab.com/ee/user/project/merge_requests/merge_when_pipeline_succeeds.html) Option, especially in the automation context, where we use lab.

 A [push option](https://docs.gitlab.com/ee/user/project/push_options.html) named `merge_request.merge_when_pipeline_succeeds` does exist for that matters.

**Comment by prarit** [comment]
I've been thinking about this same option for a while.  I'll take a look at the API and let you know if we can add this functionality.

**Comment by prarit** [comment]
There is an option to do this: https://github.com/xanzy/go-gitlab/blob/v0.47.0/merge_requests.go#L662

I'll add a 'lab mr create' option for this.  It might be wordy though ;)

**Comment by bmeneguele** [comment]
Lab, but default, have this option set. But in my workflow, it's sometimes important to merge even if the pipeline failed.. so I'm implementing right now the flag :)
@prarit, would you mind if I take this issue?

**Comment by prarit** [comment]
np!  Go for it @bmeneguele :)

**Comment by bmeneguele** [comment]
> There is an option to do this: https://github.com/xanzy/go-gitlab/blob/v0.47.0/merge_requests.go#L662
> 
> I'll add a 'lab mr create' option for this. It might be wordy though ;)

Just one note: this is under the [merge-request accpet](https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr) API and is set, today, by default with `lab mr merge`. So I'm going to keep it there instead of adding to `lab mr create`.

**Comment by galan** [comment]
Wow, you people are amazingly fast :rocket: 

Do I understand that correctly, that it is required do call lab a second time on the created MR for this feature and that it already exists?

**Comment by bmeneguele** [comment]
> Wow, you people are amazingly fast rocket
> 

Your timing was the point :D I was looking into it right at the moment you opened the issue heheh

> Do I understand that correctly, that it is required do call lab a second time on the created MR for this feature and that it already exists?

Yes, `lab mr merge <mr-id>` today set the MR flag "merge automatically iff pipeline succeeds".

However, the PR #654 turns this default behavior off: after it's merged you'll need to pass `-p` or `--pipeline-succeeds` to `lab mr merge <mr-id>` to get the same behavior. The default will be "merge immediately".

**Comment by towo** [comment]
Might want to bump version; since having figured out it does a "merge on succeed", I tend to hit it soon after the create, and that would be a painful experience if it suddenly does an immediate merge…

**Comment by bmeneguele** [comment]
> Might want to bump version; since having figured out it does a "merge on succeed", I tend to hit it soon after the create, and that would be a painful experience if it suddenly does an immediate merge…

Yeah, we're going to do that.
However, this behavior breakage might cause a lot of surprises.. @towo @galan what if we add a negative flag instead? For instance, keep the default "merge on succeed" as the default behavior and add a `--immediate` and enhance the help message to state the default behavior.

Sounds better right?

**Comment by towo** [comment]
Plus appropriate documentation that merge is by default the same as hitting the button currently on the merge request page

**Comment by prarit** [comment]
I think a negative flag is better in this case.

**Comment by bmeneguele** [comment]
Ok.. I'm going to push a new version of #654

**Comment by bmeneguele** [comment]
It's done. Feel free to review :)

**Comment by prarit** [comment]
@bmeneguele do you think you can test using podman and then let me know the result?

**Comment by bmeneguele** [comment]
hey @prarit !
Sorry.. I tested it already. just forgot to mention =(.
