### ISSUE TITLE
Add order options to issue list

### ISSUE THREAD

**Issue by PhML** [zaquestion/lab#661]
It would be nice to be able to sort issues by priority with `order_by` attribute.

**Comment by prarit** [comment]
Hey @PhML, to be clear you want these "mr list" options to be applied to "issue list", correct?

      --order string           display order (updated_at/created_at) (default "updated_at")
      --sort string            sort order (desc/asc) (default "desc")

**Comment by PhML** [comment]
@prarit precisely :-)
I think there are more order choices though.

**Comment by prarit** [comment]
There are but I was trying to keep it simple :)

**Comment by prarit** [comment]
Hey @PhML I've opened #664 to resolve this.
