### ISSUE TITLE
Support `browse` sub command on mrs, issues, and snippets

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#67]
Example using `issue`
```
lab issue browse [remote] <id>

lab issue browse # open gitlab issues in browser
lab issue browse 1 # open gitlab issue 1 in browser
```

**Comment by nkprince007** [comment]
I'm assigning this to myself, if anyone isn't working. @zaquestion

**Comment by nkprince007** [comment]
Not sure how to test this thing. Any ideas regarding how to test [this](
https://github.com/nkprince007/lab/commit/b519dd801f9a8a9e4398cedb298f05b1e4ee62f3)?
