### ISSUE TITLE
v0.21.0 fails to build on FreeBSD

### ISSUE THREAD

**Issue by swills** [zaquestion/lab#680]
I'm seeing a build failure on FreeBSD:

```
github.com/zaquestion/lab/cmd
# github.com/zaquestion/lab/cmd
cmd/util_unix.go:33:9: undefined: syscall.Dup3
```
Yes, the dup3 syscall exists, but I think you can't access it from go via `syscall`. I think you have to use `x/sys/unix` Syscall()

**Comment by bmeneguele** [comment]
@swills I think you meant v0.21.0 in the title right? :)
We don't really support FreeBSD directly, but the fix is pretty straightforward.
Let me prepare an MR for you to test.

**Comment by bmeneguele** [comment]
@swills could you checkout the PR branch and try to build it in your FreeBSD local system?
Just to make sure I'm not missing anything.

**Comment by swills** [comment]
```
github.com/zaquestion/lab/cmd
# github.com/zaquestion/lab/cmd
cmd/util_unix.go:30:9: undefined: syscall.Dup3
```

**Comment by bmeneguele** [comment]
@swills ah yes, I was aware of that, but the Golang (1.15) interface doesn't implement it.. and that's the version we're still setting as "default" for running lab. I can revisit this topic once we update for 1.16+.

But hey, many thanks for testing it so quickly :)
I'm was preparing the new release right before I saw your issue here.
It'll be included for v0.22.0.

**Comment by swills** [comment]
I believe the `syscall` package in Go is [frozen](https://docs.google.com/document/d/1QXzI9I1pOfZPujQzxhyRy6EeHYTQitKKjHfpq0zpxZs/edit) and won't change. You can access the `dup3()` syscall via [`x/sys`](https://pkg.go.dev/github.com/celo-org/sys@v0.0.0-20200816232032-1d4c3212eaf2/unix) tho.

**Comment by bmeneguele** [comment]
@swills that's a good point actually. Just noticed `Deprecated: this package is locked down` in the syscall docs.
Well, I think I'm going to revisit it for the next release then. Many thanks for the heads up! :)
