### ISSUE TITLE
Unlabel option not working for scoped labels

### ISSUE THREAD

**Issue by bokchan** [zaquestion/lab#684]
It is possible to toggle between [scoped labels](https://docs.gitlab.com/ee/user/project/labels.html#scoped-labels) by using  `--label` and `--unlabel` together. E.g. assuming the current label is  e.g. `state::Review` this will change the scoped label to `state::Merged`

    lab issue edit --unlabel state::Review --label state::Merged  <id>

However I experience that removing a label by using `--unlabel` alone does not work for [scoped labels](https://docs.gitlab.com/ee/user/project/labels.html#scoped-labels). I.e. the command below succeeds but the label is not removed on the ticket. 

    lab issue edit --unlabel state::Review <id>

Version installed: 0.22.0

**Comment by bokchan** [comment]
Figured out that clearing the scoped label does work if you pass an empty string as new label:

    lab issue edit --unlabel state::Review  --label "" 123

**Comment by bmeneguele** [comment]
First of all, thanks for the report @bokchan.
The `--unlabel` should work by itself, without requiring a new empty label.
That's for sure a bug. I'll take a look on that and prepare a MR if possible.

**Comment by bmeneguele** [comment]
Should be fixed now.
Once again, thanks for the report.

**Comment by bokchan** [comment]
Great. Thanks for your great work @bmeneguele
