### ISSUE TITLE
mr un/approve: If -F, un/approve completes even if file read failed

### ISSUE THREAD

**Issue by zampierilucas** [zaquestion/lab#708]
When using the -F, file, option, if the file read failed for any reason, the operation continues, ignoring the file comment.
In the example below, the user will unapprove the MR without submitting the message that he wanted.
```console
lzampier@trusty:~$ lab mr unapprove origin -F a_file_that_doest_exists
2021/07/02 10:53:46 ERROR: note_common.go:25: open a_file_that_doest_existis: no such file or directory
```
![image](https://user-images.githubusercontent.com/25491728/124285112-fffc5f80-db23-11eb-97e6-1ee30d0cc37e.png)

it is possible that the same problem may occur in other parts of Lab that provides the `-F` option, a global solution for that would be:
```diff
diff --git a/cmd/note_common.go b/cmd/note_common.go
index 789c3a9..08da617 100644
--- a/cmd/note_common.go
+++ b/cmd/note_common.go
@@ -4,6 +4,7 @@ import (
        "bytes"
        "fmt"
        "io/ioutil"
+       "os"
        "runtime"
        "strconv"
        "strings"
@@ -23,6 +24,7 @@ func createNote(rn string, isMR bool, idNum int, msgs []string, filename string,
                content, err := ioutil.ReadFile(filename)
                if err != nil {
                        log.Fatal(err)
+                       os.Exit(1)
                }
                body = string(content)
        } else {
```
Should Lab take care of that? if so let me know so I can do further testing and can submit a PR :)

**Comment by zampierilucas** [comment]
@bmeneguele @prarit any input on this one? :)

**Comment by prarit** [comment]
Huh, I thought the log.Fatal(err) would have stopped lab.  But yes, an os.Exit(1) there is fine.

**Comment by zampierilucas** [comment]
@prarit on a quick search, I found that log.Fatal() __should__ call os.Exit(1).
I will investigate further this issue

**Comment by bmeneguele** [comment]
Oh, yes. The `log.Fatal()` calls the `os.Exit()` it should not help to solve the problem.
The issue here might be the way `log.Fatal()` works, it doesn't close file descriptors nor running deferred code.
#729 might be related.

**Comment by bmeneguele** [comment]
> Oh, yes. The `log.Fatal()` calls the `os.Exit()` it should not help to solve the problem.

Just to clarify: even though we have a custom log layer, our `log.Fatal()` still calls the default golang/logging `log.Fatal()`, so the behavior is kept.

https://github.com/zaquestion/lab/blob/833faebfaed0adde96ab9fdd55ab2039d48eb1d7/internal/logger/logger.go#L117-L133
