### ISSUE TITLE
mr show: --since seems to be broken

### ISSUE THREAD

**Issue by zampierilucas** [zaquestion/lab#710]
Something might be changed on `--since` filter for `lab mr show`, since I cannot filter by date anymore.

<details>
    <summary>Example!</summary>
    
    ❯ lab mr show origin -c -M --since "2021-07-06 19:08:50.000 +0000 UTC" --no-pager
    !29 hello \nworld
    ===================================
    world\n  hello
    iaaaaa
    -----------------------------------
    Project: lzampier/kernel-test
    Branches: gitlab_test->main
    Status: Open
    Assignee: None
    Author: lzampier
    Approved By: None
    Approvers: None
    Approval Groups: None
    Reviewers: None
    Milestone: None
    Labels: None
    Issues Closed by this MR:
    Subscribed: Yes
    WebURL: https://gitlab.com/lzampier/kernel-test/-/merge_requests/29
    * lzampier changed title from **{-aaa-}** to **{+hello \nworld+}** at 2021-07-06 14:21:10.375 +0000 UTC
    * lzampier changed the description at 2021-07-06 14:21:10.416 +0000 UTC
    * lzampier changed title from **hello \nworld** to **hello \nworld{+adadqadasdqwe+}** at 2021-07-06 14:29:45.434 +0000 UTC
    * lzampier changed the description at 2021-07-06 14:29:45.484 +0000 UTC
    * lzampier changed title from **hello \nworld{-adadqadasdqwe-}** to **hello \nworld** at 2021-07-06 14:29:51.52 +0000 UTC
    * lzampier changed the description at 2021-07-06 14:29:51.61 +0000 UTC
    -----------------------------------
    #619977909: lzampier commented at 2021-07-06 19:08:49.222 +0000 UTC
    
    a comment
    -----------------------------------
    #619978132: lzampier commented at 2021-07-06 19:09:09.525 +0000 UTC
    
    another one
</details>

**Comment by zampierilucas** [comment]
The same problem occurs on `lab issue show`.

**Comment by prarit** [comment]
Odd, I'll take a look today.  I'm sure it's something trivial as it does work when using `lab mr show --comments`.

**Comment by prarit** [comment]
The issue here is that the timezone is expected to be UTC in the input and the output.  I've tried to document that in the help for the command.

**Comment by zampierilucas** [comment]
@prarit Are you saying the format on the example is wrong?

**Comment by prarit** [comment]
It's tough to see on the page.  Are the dates "highlighted" after 2021-07-06 19:08:50.000 +0000 UTC ?

**Comment by prarit** [comment]
Wait ... It just occurred to me what might be wrong.  Are you thinking that the --since command will only print comments after a certain date?

**Comment by zampierilucas** [comment]
@prarit YES!! wait, is it's not like that?

**Comment by prarit** [comment]
No. It doesn't work like that.  It only highlights comments after the date.

**Comment by zampierilucas** [comment]
@prarit  Ok then, my apologies then, I will close this then.
