### ISSUE TITLE
manual job is launched when ESC is used to cancel the prompt

### ISSUE THREAD

**Issue by davinkevin** [zaquestion/lab#712]
Hi, 

In a pipeline visualisation, on a manual job, if I hit `r` to launch one I have the following screen:

![image](https://user-images.githubusercontent.com/1970922/124709094-63f39f00-defb-11eb-9ed7-f4c83d17dc0e.png)

If I use `ESC` to cancel the prompt, the job is launched by `lab` 😓. 

I don't know what to add to this issue, which seem to be pretty basic. Let me know if you need some extra information. 

Thanks ❤️ !

**Comment by bmeneguele** [comment]
Yeah, that's unfortunate.
I never really dove into this part of the code. But the way it's implemented turns the "yes" option, indirectly, the default option when nothing is set. I think that when it was coded no one really thought about hitting ESC :). It seems an easy fix though.

I'm fixing other small issues across the CI code, I might take care of this one too.

Thanks for the report @davinkevin

**Comment by davinkevin** [comment]
Thank you !

**Comment by zaquestion** [comment]
oh goodness, that's horrid, almost certainly a miss on my part, that `ci view` stuff is kinda sketchy. sorry! I hope the consequence of this didn't break anything too badly 🙏

**Comment by davinkevin** [comment]
Not for me, but some were surprised… hopefully they can restart the pipeline to rebuild the infrastructure 😇.

**Comment by zaquestion** [comment]
Fix in https://github.com/zaquestion/lab/pull/719

**Comment by zaquestion** [comment]
Not sure if the bug or the fix is more embarrassing, this cup of shame run'th deep for sure. Thanks for being such a long time user @davinkevin ! ❤️

**Comment by bmeneg** [comment]
Oops, we forgot to close this issue back when the fix was released.
Closing it.
