### ISSUE TITLE
CI Pipeline interface

### ISSUE THREAD

**Issue by nkprince007** [zaquestion/lab#74]
**NOTICE: Description fully cannibalized by** @zaquestion
Still debating if such a thing should be in lab, but could always move it into its own tool and be called by lab.
Support
- Running jobs
- Viewing jobs status (live)
- Viewing environments
  - Include re-deploying jobs

Also add `lab ci lint` command
Ref: https://docs.gitlab.com/ce/api/lint.html

**Comment by zaquestion** [comment]
What would the editor workflow look like?

**Comment by zaquestion** [comment]
Also started working on a `ci` sub command. We could support this through `lab ci validate`

**Comment by nkprince007** [comment]
Maybe we can't include editor workflow here, since the API doesn't show where the error is.

**Comment by zaquestion** [comment]
![a_start](https://user-images.githubusercontent.com/2358914/34144360-123304de-e446-11e7-8faa-14826b46dbd6.png)
From: https://gitlab.com/zaquestion/test/pipelines/15273642

Using https://github.com/jroimartin/gocui

**Comment by nkprince007** [comment]
That looks cool, can we maybe have some colours and arrows?

**Comment by zaquestion** [comment]
Still static, but we're getting there!
![lab_ci](https://user-images.githubusercontent.com/2358914/34207592-032c7218-e540-11e7-9daf-d9d4c5989338.png)

From: https://gitlab.com/zaquestion/test/pipelines/15273642

**Comment by zaquestion** [comment]
Put this up in an effort to support `lab ci lint`. https://github.com/xanzy/go-gitlab/pull/293

I've already written a working implementation with those changes. Once the API is exposed should be able to bring in the functionality in short order.

**Comment by zaquestion** [comment]
Also relying on these changes for the pipeline interface: https://github.com/jroimartin/gocui/pull/130

**Comment by zaquestion** [comment]
Have mostly replicated the current progress in https://github.com/rivo/tview which has been nicer to work with overall. 
![tview_ci_pipeline](https://user-images.githubusercontent.com/2358914/36411456-94fc1a26-15ca-11e8-90fe-2a18bbef6ad9.png)

- [ ] fix the rendering overall (notice the extra lines on the right most side)
- [ ] test live updating (implemented but not yet useful)
- [ ] screen doesn't clear when resizing (or between all updates?)
- [ ] Long term solution for drawing the lines (currently have tview hacked up to expose the screen to me)

**Comment by zaquestion** [comment]
Latest look
![pipeline](https://user-images.githubusercontent.com/2358914/39100905-88d1ed28-4646-11e8-980d-86a7340d4143.png)

**Comment by zaquestion** [comment]
The above has been released in `0.11.0` under `lab ci view` as a beta feature.

Also `lab ci trace` was release in `0.11.0` for viewing ci job logs in realtime!

**Comment by twouters** [comment]
Is there a way to close the view (except for <kbd>Ctrl-c</kbd>)?
Would be nice if we can use <kbd>Esc</kbd> and/or <kbd>q</kbd> to close the view.

**Comment by zaquestion** [comment]
@twouters Thanks for the feedback, I've added support for exiting with <kbd>q</kbd> and <kbd>esc</kbd> in `0.11.1`.

**Comment by zaquestion** [comment]
Put https://github.com/lunixbochs/vtclean/pull/7 up to support cleaning gitlab's trace file response. Hopefully that gets merged in and we can use it directly, but I'll give it a week while I get the remaining changes together in lab. Code for running/retrying jobs has been written and seems to function (pending tests). The vtclean change is to support viewing trace logs in the pipeline interface, which is mostly coded up, but has some formating issues due to the escape sequences returned in the API

**Comment by zaquestion** [comment]
Going to call this good as of https://github.com/zaquestion/lab/pull/175, any future bugs or features will be tracked in new issues.
