### ISSUE TITLE
Raise an error (or a warning) if a provided file is inaccessible

### ISSUE THREAD

**Issue by jdmichaud** [zaquestion/lab#742]
If the file provided to the `--file` option is not accessible (no read access or wrong path) `lab` just fails silently as if no file were provided. It makes troubleshooting more difficult than it needs to be, for example if there is subtle typo in the path.

Raising an error or at least a warning that the provided file is invalid would enhance the user experience.

**Comment by zampierilucas** [comment]
@jdmichaud Thank you for your issue :D, I'm dealing with something similar in https://github.com/zaquestion/lab/issues/708, but I do get a warning when the path is wrong, which command are you experience this issue?

**Comment by jdmichaud** [comment]
@zampierilucas If I am doing this:
```bash
lab mr create --file /non/existent/file
```
And I get this error:
```bash
2021/09/22 08:10:34 ERROR: mr_create.go:234:aborting MR due to empty MR msg
```
If I were to call `lab me create` with no additional option, I would get the same error message. If `lab` were to explicitly warn of inaccessible file, it would improve the UX experience.

**Comment by prarit** [comment]
This should be easy to warn on.  I'll take a look.
