### ISSUE TITLE
Support  edit functionality on mrs, issues, and snippets

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#76]
Wondering if this should be a `edit` sub command or a flag `--amend` (like git)

Want to support setting/updating properties without having to edit the message. The flag approach would make sense to use `--no-edit`. Not sure the best choice for the sub command route...

That said, leaning towards the sub command to be consistent with other commands, and optionally support `--amend` as the flag off the parent command.

**Comment by cuthix** [comment]
I very often just need change text or tick/untick part of issue, so would be nice to have command/flag to edit issue text :)

**Comment by claytonrcarter** [comment]
@zaquestion I'm tinkering with this and would like some feedback on the behavior and and flag naming. I'm aiming for parity/familiarity with the various `lab ... create` commands, i.e. title/description/labels/assignees. Here's the help text so far:

```
$ ./lab issue edit -h
Edit or update an issue

Usage:
  lab issue edit [remote] <id> [flags]

Aliases:
  edit, update

Flags:
  -a, --assign strings     Add an assignee by username
      --edit               Open the issue in an editor (default if no other flags given)
  -h, --help               help for edit
  -l, --label strings      Add the given label(s) to the issue
  -m, --message strings    Use the given <msg>; multiple -m are concatenated as separate paragraphs
  -t, --title string       Set the issue title
  -A, --unassign strings   Remove an assigne by username
  -L, --unlabel strings    Remove the given label(s) from the issue
```

### Specific Questions

1. I wanted to add a flag to just change the title, hence `--title`, but this seems to beg for `--description` flags, too. How would something like that interact with the `--message` flags (which are standard on `lab issue create`, `lab issue note`, `lab mr create`, etc). Adding `--description` would be more declarative, which might be appropriate for an `edit` command, but it could be confusing if `--message` is left in place. On the other hand, if `--message` is removed, the syntax would break from the `create` commands, which doesn't sound great either.
2. Do the capital shorthands for unassigned and unlabel sound OK?

### Usage Examples

Edit issue in editor: `lab issue edit <id>`  
Only update issue title:  `lab issue edit <id> -t "new title"` or: `lab issue edit <id> -m "new title"`  
Only add label to issue:  `lab issue edit <id> -l newlabel`  
Add label to issue and edit title/description in editor:  `lab issue edit <id> -l newlabel --edit`

**Comment by zaquestion** [comment]
1. Leaning towards just using the `-m` notation, as in `lab issue edit <id> -m "new title" -m "new description"` -- I think it makes sense to not update the description if a second `-m` isn't sent. This seems intuitive to me, but I'd call it out in the docs. Likewise it seems like we should only open the editor if no flags are passed, vs supporting a `--edit` flag. In your last example this would mean 2 separate commands, which seems reasonable to me. 

2. Seems weird at a glance. How does the API enforce these? Off the cuff I'm thinking we should just use the same flags, but have them operate as a toggle if thats how the API works anyways. Otherwise, perhaps we just shouldn't have shorthands for those flags.

**Comment by zaquestion** [comment]
Yeah, just dropping the short hand and using separate flags seems better than toggling.

**Comment by bmeneguele** [comment]
Edition for MRs and Issue is now available. Snippets aren't yet, but we can handle that in a separate issue re-using the code already existent for both MRs and Issues. I'm going to close this issue here.
