### ISSUE TITLE
When running `lab` in a directory where there is a `lab` file it fails

### ISSUE THREAD

**Issue by JohnVillalovos** [zaquestion/lab#766]
```
$ lab --version
lab version 0.23.0
```

I make an empty file named `lab` in my directory.

```
$ touch lab
$ ls -l
total 0
-rw-r--r--. 1 jlvillal jlvillal 0 Dec  6 13:04 lab
```

`lab` gets run from a different directory.

```
$ which lab
~/.local/bin/lab
$ lab
Error: User authentication failed.  This is likely due to a misconfigured Personal Access Token.  Verify the token or token_load config settings before attempting to authenticate.
```

Delete the empty `lab` file and it works

```
$ rm lab
$ lab
lab: A GitLab Command Line Interface Utility

Usage:
  lab [flags]
  lab [command]
<snip>
```

# 😵

**Comment by prarit** [comment]
This occurs because in earlier versions of 'lab' the ./lab file was used as a config file that held the GitLab Token.  This file has been moved to .config/lab/lab.toml, however, we still support the old config file for old versions.

**Comment by prarit** [comment]
And :) :) HOW ARE THINGS GOING JOHN?! :)

**Comment by JohnVillalovos** [comment]
> And :) :) HOW ARE THINGS GOING JOHN?! :)

Hey Prarit! Things are going well 😊. I enjoyed watching your presentation about Gitlab and the RHEL kernel process you and DonZ did for devconf.cz a year or two ago.

Thanks for the explanation. Maybe that functionality could be deprecated? Doing `--debug` gave no info on what was going on so I was a bit confused.

**Comment by JohnVillalovos** [comment]
As a note. I went and tested this on tip and it actually works. So I decided to `git bisect` it because I was bored.

The commit that fixed this issue is:

```
commit 014c61581e1888bdf48fa60b70eeaf3d636431b1
Author: Prarit Bhargava <prarit@redhat.com>
Date:   Wed Oct 13 19:15:03 2021 -0400
```

**Comment by JohnVillalovos** [comment]
This was fixed by: https://github.com/zaquestion/lab/pull/753

Closing and hoping for a new release soon-ish.
