### ISSUE TITLE
lab shouldn't change a MR status when no status change is specified

### ISSUE THREAD

**Issue by cmaiolino** [zaquestion/lab#772]
When using lab tool to edit a MR in "draft" status, the tool also ended up implicitly changing the MR status from 'draft' to 'ready'.
Unless --ready or --draft is specified, IMHO the lab tool shouldn't be changing the MR status.

**Comment by bmeneg** [comment]
Ok, I second your opinion that lab should preserve the state there.
I already saw where in the code we can have it resolved. Will prepare the PR and submit it asap.

Many thanks for the report @cmaiolino

**Comment by bmeneg** [comment]
Oh, I just noticed that it should not be possible per lab code.
The draft state is selected based on the title prefix ("Draft:"), following how GitLab checks it.
If you remove that prefix, GitLab will move the MR to "ready". Annoying? Yeah, pretty much, I agree :-(

**Comment by cmaiolino** [comment]
> Oh, I just noticed that it should not be possible per lab code. The draft state is selected based on the title prefix ("Draft:"), following how GitLab checks it. If you remove that prefix, GitLab will move the MR to "ready". Annoying? Yeah, pretty much, I agree :-(

Great! Sorry the noise then, and thanks for the heads up about it... 'Draft' mode depends on the MR's subject :)

Cheers!
