### ISSUE TITLE
lab 0.23.0: `mr show -c' fails in git worktree

### ISSUE THREAD

**Issue by github-cygwin** [zaquestion/lab#773]
Hi,

I just encountered the issue from the subject line.  While
`lab mr show <MR#>`
works nicely in a worktree,
`lab mr show -c <MR#>`
fails with ERROR: config.go:364: open .git/lab/lab.toml: not a directory
The reason is apparently that .git is a file in a worktree, rather than a directory.  Looks like following the gitdir info in the worktree .git file is not implemented yet?

Corinna

**Comment by bmeneg** [comment]
Hi Corinna,

We already have the code for following the gitdir, but it isn't being used where it should.
I'm going to submit a PR correcting it.
