### ISSUE TITLE
About text should be updated to remove reference to usage as a wrapper

### ISSUE THREAD

**Issue by JohnVillalovos** [zaquestion/lab#777]
Currently the "About" text says:

```
About

Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab 
```

From my understanding the project has moved away from recommending `lab` as a wrapper around `git`.

This is the "About" text seen when going to: https://github.com/zaquestion/lab

**Comment by JohnVillalovos** [comment]
And probably the README should be updated also to remove examples of using as a wrapper.

**Comment by bmeneg** [comment]
@JohnVillalovos yes, well pointed!
This rewording should've happened some time ago already.
I'll add it to my TODO list for next week.

**Comment by prarit** [comment]
@bemeng, did you get this done?

**Comment by bmeneg** [comment]
@prarit not yet. But will do.

**Comment by JohnVillalovos** [comment]
@bmeneg 

The About text on the page https://github.com/zaquestion/lab still says it should be used as a wrapper:

![image](https://user-images.githubusercontent.com/578155/166300739-a8dab66a-8403-4e89-9108-a7724790d11d.png)

**Comment by bmeneg** [comment]
Oops, that's something we need help from someone else: @zaquestion we merged the new readme file some time ago, would you mind updating the "about" words?
