### ISSUE TITLE
editor starts on non-editing commands

### ISSUE THREAD

**Issue by prarit** [zaquestion/lab#790]
@bmeneg, commit 66c580f8cf16 ("cmd/edit: accept linebreak flag for editing description") significantly changed the behavior of the 'lab mr edit' command.  Previous to this commit, 'lab mr edit --ready' or 'lab mr edit --draft' or 'lab mr edit --reviewer' would not open up an editor.

After the commit, the editor ALWAYS opens.  This code likely should not have been removed:
```
-       // if other flags were given (eg label), then skip the editor and return
-       // what we already have
-       if nFlag != 0 {
-               return title, body, nil
-       }
-
```

**Comment by bmeneg** [comment]
Ooops. That's, for sure, not what I wanted to do. That's really strange.
Let me fix it real quick!

**Comment by bmeneg** [comment]
@prarit I tested it locally and seems to be working as expected and as we talked before.
I'm going to merge the PR to avoid surprises to other users. If you test it later and find any other issues, please let me know.
