### ISSUE TITLE
README: Link to syntax for the TOML config

### ISSUE THREAD

**Issue by hoijui** [zaquestion/lab#805]
.. or give help in any other way, where the TOML config is first mentioned, about how the config file should look like.

**Comment by hoijui** [comment]
great project btw. thank you! :-)

**Comment by prarit** [comment]
Great suggestion @hoijui.  

Would an example like

```
[core]
  host = "https://gitlab.com"
  token = "1223334444555556789K"
  user = "yourusername"

[mr_checkout]
  force = true

[mr_create]
  force-linebreak = true
  draft = true

[mr_edit]
  force-linebreak = true
```

work for you?

**Comment by hoijui** [comment]
> Great suggestion @hoijui.
> 
> Would an example like
> 
> ```
> [core]
>   host = "https://gitlab.com"
>   token = "1223334444555556789K"
>   user = "yourusername"
> 
> [mr_checkout]
>   force = true
> 
> [mr_create]
>   force-linebreak = true
>   draft = true
> 
> [mr_edit]
>   force-linebreak = true
> ```
> 
> work for you?

that looks good! :-)
If there were also a link to all the possible settings or something like that, I would be fully satisfied.

**Comment by hoijui** [comment]
though @bmeneg 's suggestion also sounds good.. I certainly don;t know about it. ;-)

**Comment by prarit** [comment]
> I think the README deserves an highlight about the "setting default flags for commands" subject. IMHO that's something that only those aware of how go-cobra and go-viper works know how to set them smile

Yeah :)  Perhaps a sentence indicating that any option can be set, and then a pointer to the simple example file above?

**Comment by hoijui** [comment]
how do I know what "any option" means.. I would need a list of them.

**Comment by bmeneg** [comment]
@hoijui any option == any available flag in the `--help`. The list would be exactly all the flags. Some of them makes sense to have a default value set, others done, but every flag can be set in the configuration file. Do you think that using "flag" instead of "option" would be clearer?

**Comment by prarit** [comment]
> how do I know what "any option" means. I think would need a list of them.

The --help commands will provide this for you.  Let me fix the text to indicate that.

**Comment by prarit** [comment]
Fixed.

**Comment by hoijui** [comment]
AHA!! :O
YES! now it is perfect, thank you for the change, and you both for the explanation!
I honestly did not understand, it was about the CLI flags/options!

This issue should be closed when https://github.com/zaquestion/lab/pull/807 is merged.
