### ISSUE TITLE
Handwritten changelog

### ISSUE THREAD

**Issue by SuperSandro2000** [zaquestion/lab#814]
The auto generated changelog which only contains the commits is not useful. A handwritten one with the most important topics would be way more useful.

**Comment by SuperSandro2000** [comment]
I am talking about https://github.com/zaquestion/lab/releases/tag/v0.24.0. I am not sure if there are new features which I should know or if there are some deprecations and if I need to change some commands.

**Comment by bmeneg** [comment]
@SuperSandro2000 100% agreed. Thanks for the report!
We should've already moved from this bad behavior of letting the commits there as is.
Another annoying thing we need to do is to run new releases more often, thus easing everyone's life on checking what changed from one version to another.

Starting on the next release (0.25.0.... or 1.0 ?? (🤯)) I'll make sure to make the release notes *useful* with actual handwritten bullet points. Sounds good?

**Comment by bmeneg** [comment]
@SuperSandro2000 hopefully https://github.com/zaquestion/lab/releases/tag/v0.25.0 looks better 🤞

**Comment by SuperSandro2000** [comment]
That looks much better! Thank you!
