### ISSUE TITLE
mr create: accept default MR description

### ISSUE THREAD

**Issue by joe-lawrence** [zaquestion/lab#819]
We open new MRs with a command like:
```
$ lab mr create --force-linebreak --draft <remote> <target_branch>
```
and always use the default description that is loaded in the editor.  Is there a way to accept the default MR description from the command line?

Alternatively, should we just do something like?
```
$ lab mr create -F <(git show -1) ...
```

**Comment by bmeneg** [comment]
Both are valid, but I think the idea of having a `--no-edit` (like `git commit` has) builtin seems reasonable to me.
@prarit @zampierilucas what do you think? I can work on that if you guys agree with the proposal.

**Comment by prarit** [comment]
IIRC 'lab mr create' behaves exactly like the webUI does.  If the number of commits is 1, then it defaults to using the commit description.  If the number of commits is greater than one then an empty title and description are provided.  The problem with changing this behavior is that we would be different than the webUI and I don't think that's what we want with the tool.  I do, however, agree that a -F option isn't a bad thing for the command line.

**Comment by bmeneg** [comment]
@prarit, so, instead of 
```
$ lab mr create
        <edit opens with MR desc pre-populated>
        <user quits editor w/o editing the pre-populated desc>
<new MR URL>
$
```
we would have 
```
$ lab mr create --no-edit
        <use default text generated by lab itself>
<new MR URL>
$
```
Meaning no user interaction.

**Comment by prarit** [comment]
I see.  So the name is confusing to me.  Could we change that to --no-editor?

**Comment by bmeneg** [comment]
I used `--no-edit` because that's the flag name used on git itself, ie. `git commit --amendo --no-edit`, making it easier for those used to use this flag there. But we can start with `--no-editor`.

**Comment by zampierilucas** [comment]
IMO this is a great feature, I'm not sure how we took so long to add it :p
Also I would vouch for `--no-edit`, for the same reason as Bruno, I'm used to it because of git.

**Comment by prarit** [comment]
Okey-doke "no-edit" wins :)
