### ISSUE TITLE
`lab mr create` from local branch

### ISSUE THREAD

**Issue by MartinDelille** [zaquestion/lab#841]
I'm using both `lab` and [Github cli](https://github.com/cli/cli) and one thing that I find very convenient with `gh` is the ability to create a pull request from a local branch that has not been pushed yet to a remote.

Would it be possible with `lab` ?

**Comment by prarit** [comment]
@MartinDelille my apologies for not getting back to you.  It's been several months :(

I think we should be able to do that.  Does the Github cli auto-detect that the branch hasn't been pushed?

**Comment by MartinDelille** [comment]
Yes. In fact I'm now using https://gitlab.com/gitlab-org/cli for that.

**Comment by prarit** [comment]
I dug into this a bit.  https://gitlab.com/gitlab-org/cli makes some assumptions about the git layout that may not necessarily be correct for all users. [Aside: that also explains why the gitlab cli tool doesn't always work for me :( ] In the past we have had users who have multiple remotes and 'pushing' to the correct repo becomes questionable.

**Comment by MartinDelille** [comment]
Ok let's close this issue.
