### ISSUE TITLE
install script doesn't work on linux.

### ISSUE THREAD

**Issue by tutuca** [zaquestion/lab#96]
On ubuntu 17.10 with go version `go1.9.1 linux/amd64`. running the install script gets:

```
./install.sh: 4: ./install.sh: [[: not found
+ go get -u -d github.com/zaquestion/lab
+ cd /src/github.com/zaquestion/lab
./install.sh: 9: cd: can't cd to /src/github.com/zaquestion/lab
```
I'm not really a gopher so I don't get why is searching for source files in that path.
How do I get around this to install `lab`?

somewhat related PD: Is there a way to provide linux binaries?

**Comment by zaquestion** [comment]
@tutuca you can download the latest release as a pre-built binary here: https://github.com/zaquestion/lab/releases/tag/v0.9.0

I just noticed this issue today as well, I'm going to update the install script to just use the prebuilt binaries

**Comment by zaquestion** [comment]
@tutuca Updated the install script to use the release binaries, you should be able to use 
```
curl -s https://raw.githubusercontent.com/zaquestion/lab/master/install.sh | bash
```

**Comment by tutuca** [comment]
Lovely, thanks!
